/**
 * Comprehensive syntax definitions for 50+ programming languages.
 * Each definition provides keywords, builtins, comment styles, and string delimiters
 * used by the content renderer for syntax-aware text processing.
 */

export interface LanguageDefinition {
  name: string;
  keywords: string[];
  builtins: string[];
  commentSingle: string;
  commentMulti: [string, string];
  stringChars: string[];
  caseInsensitive?: boolean;
}

export const EXTENDED_LANGUAGES: Record<string, LanguageDefinition> = {
  // ─── Web: HTML ────────────────────────────────────────────────
  html: {
    name: "HTML",
    keywords: [
      "html", "head", "body", "title", "meta", "link", "style", "script",
      "div", "span", "p", "a", "img", "ul", "ol", "li", "table", "tr",
      "td", "th", "thead", "tbody", "tfoot", "form", "input", "button",
      "select", "option", "textarea", "label", "fieldset", "legend",
      "h1", "h2", "h3", "h4", "h5", "h6", "header", "footer", "nav",
      "main", "section", "article", "aside", "figure", "figcaption",
      "details", "summary", "dialog", "template", "slot", "canvas",
      "video", "audio", "source", "track", "iframe", "embed", "object",
      "map", "area", "pre", "code", "blockquote", "br", "hr", "noscript",
    ],
    builtins: [
      "class", "id", "style", "href", "src", "alt", "title", "type",
      "name", "value", "placeholder", "disabled", "readonly", "required",
      "hidden", "autofocus", "autoplay", "controls", "loop", "muted",
      "width", "height", "min", "max", "step", "pattern", "maxlength",
      "action", "method", "enctype", "target", "rel", "media", "sizes",
      "crossorigin", "integrity", "async", "defer", "charset", "content",
      "http-equiv", "lang", "dir", "tabindex", "role", "aria-label",
      "data-", "draggable", "contenteditable", "spellcheck", "translate",
    ],
    commentSingle: "",
    commentMulti: ["<!--", "-->"],
    stringChars: ['"', "'"],
  },

  // ─── Web: CSS ─────────────────────────────────────────────────
  css: {
    name: "CSS",
    keywords: [
      "color", "background", "background-color", "background-image",
      "background-size", "background-position", "background-repeat",
      "border", "border-radius", "border-color", "border-width",
      "border-style", "border-top", "border-right", "border-bottom",
      "border-left", "margin", "margin-top", "margin-right",
      "margin-bottom", "margin-left", "padding", "padding-top",
      "padding-right", "padding-bottom", "padding-left", "width",
      "height", "min-width", "max-width", "min-height", "max-height",
      "display", "position", "top", "right", "bottom", "left",
      "float", "clear", "overflow", "overflow-x", "overflow-y",
      "font-family", "font-size", "font-weight", "font-style",
      "line-height", "text-align", "text-decoration", "text-transform",
      "text-indent", "text-shadow", "letter-spacing", "word-spacing",
      "white-space", "vertical-align", "flex", "flex-direction",
      "flex-wrap", "flex-flow", "justify-content", "align-items",
      "align-self", "align-content", "grid", "grid-template-columns",
      "grid-template-rows", "grid-gap", "gap", "box-shadow",
      "opacity", "visibility", "z-index", "cursor", "transition",
      "transform", "animation", "list-style", "list-style-type",
      "content", "outline", "resize", "user-select", "box-sizing",
      "filter", "backdrop-filter", "clip-path", "mask", "object-fit",
      "scroll-behavior", "appearance", "contain", "break-inside",
    ],
    builtins: [
      "!important", "@media", "@keyframes", "@import", "@font-face",
      "@supports", "@layer", "@container", "@page", "@charset",
      "inherit", "initial", "unset", "revert", "auto", "none",
      "block", "inline", "inline-block", "flex", "grid", "inline-flex",
      "inline-grid", "table", "table-cell", "table-row", "relative",
      "absolute", "fixed", "sticky", "static", "solid", "dashed",
      "dotted", "double", "hidden", "scroll", "visible", "transparent",
      "nowrap", "wrap", "pre", "pre-wrap", "pre-line", "center",
      "left", "right", "justify", "space-between", "space-around",
      "space-evenly", "stretch", "baseline", "start", "end",
      "var()", "calc()", "min()", "max()", "clamp()", "url()",
      "rgb()", "rgba()", "hsl()", "hsla()", "linear-gradient()",
      "radial-gradient()", "conic-gradient()", "repeat()",
    ],
    commentSingle: "",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Web: JavaScript ──────────────────────────────────────────
  javascript: {
    name: "JavaScript",
    keywords: [
      "break", "case", "catch", "class", "const", "continue",
      "debugger", "default", "delete", "do", "else", "export",
      "extends", "finally", "for", "function", "if", "import",
      "in", "instanceof", "let", "new", "of", "return", "static",
      "super", "switch", "this", "throw", "try", "typeof",
      "var", "void", "while", "with", "yield", "async", "await",
      "enum", "implements", "interface", "package", "private",
      "protected", "public", "from", "as", "get", "set",
    ],
    builtins: [
      "console", "window", "document", "Math", "JSON", "Promise",
      "Array", "Object", "String", "Number", "Boolean", "Symbol",
      "BigInt", "RegExp", "Error", "TypeError", "RangeError",
      "SyntaxError", "ReferenceError", "Map", "Set", "WeakMap",
      "WeakSet", "Date", "parseInt", "parseFloat", "isNaN",
      "isFinite", "undefined", "null", "NaN", "Infinity",
      "setTimeout", "setInterval", "clearTimeout", "clearInterval",
      "fetch", "requestAnimationFrame", "AbortController",
      "Proxy", "Reflect", "globalThis", "arguments",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ["'", '"', "`"],
  },

  // ─── Web: TypeScript ──────────────────────────────────────────
  typescript: {
    name: "TypeScript",
    keywords: [
      "break", "case", "catch", "class", "const", "continue",
      "debugger", "default", "delete", "do", "else", "export",
      "extends", "finally", "for", "function", "if", "import",
      "in", "instanceof", "let", "new", "of", "return", "static",
      "super", "switch", "this", "throw", "try", "typeof",
      "var", "void", "while", "with", "yield", "async", "await",
      "enum", "implements", "interface", "package", "private",
      "protected", "public", "from", "as", "get", "set",
      "type", "namespace", "declare", "abstract", "readonly",
      "keyof", "infer", "is", "asserts", "never", "unknown",
      "unique", "satisfies", "using", "await",
    ],
    builtins: [
      "console", "window", "document", "Math", "JSON", "Promise",
      "Array", "Object", "String", "Number", "Boolean", "Symbol",
      "BigInt", "RegExp", "Error", "TypeError", "RangeError",
      "SyntaxError", "Map", "Set", "WeakMap", "WeakSet", "Date",
      "Partial", "Required", "Readonly", "Record", "Pick", "Omit",
      "Exclude", "Extract", "NonNullable", "ReturnType",
      "InstanceType", "Parameters", "ConstructorParameters",
      "Uppercase", "Lowercase", "Capitalize", "Uncapitalize",
      "setTimeout", "setInterval", "fetch", "AbortController",
      "globalThis", "any", "void", "never", "unknown",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ["'", '"', "`"],
  },

  // ─── Web: JSX ─────────────────────────────────────────────────
  jsx: {
    name: "JSX",
    keywords: [
      "break", "case", "catch", "class", "const", "continue",
      "debugger", "default", "delete", "do", "else", "export",
      "extends", "finally", "for", "function", "if", "import",
      "in", "instanceof", "let", "new", "of", "return", "static",
      "super", "switch", "this", "throw", "try", "typeof",
      "var", "void", "while", "with", "yield", "async", "await",
      "from", "as", "get", "set", "typeof",
    ],
    builtins: [
      "React", "Component", "useState", "useEffect", "useRef",
      "useCallback", "useMemo", "useContext", "useReducer",
      "useLayoutEffect", "Fragment", "StrictMode", "Suspense",
      "createElement", "cloneElement", "Children", "Props",
      "key", "ref", "className", "onChange", "onClick",
      "onSubmit", "onKeyDown", "onKeyUp", "onFocus", "onBlur",
      "dangerouslySetInnerHTML", "style", "htmlFor", "defaultValue",
      "console", "Math", "JSON", "Promise", "Array", "Object",
      "String", "Number", "Boolean", "Error", "Map", "Set",
      "undefined", "null", "true", "false", "NaN", "Infinity",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ["'", '"', "`"],
  },

  // ─── Web: TSX ─────────────────────────────────────────────────
  tsx: {
    name: "TSX",
    keywords: [
      "break", "case", "catch", "class", "const", "continue",
      "debugger", "default", "delete", "do", "else", "export",
      "extends", "finally", "for", "function", "if", "import",
      "in", "instanceof", "let", "new", "of", "return", "static",
      "super", "switch", "this", "throw", "try", "typeof",
      "var", "void", "while", "with", "yield", "async", "await",
      "enum", "implements", "interface", "package", "private",
      "protected", "public", "from", "as", "get", "set",
      "type", "namespace", "declare", "abstract", "readonly",
      "keyof", "infer", "is", "asserts", "never", "unknown",
      "unique", "satisfies", "using",
    ],
    builtins: [
      "React", "Component", "useState", "useEffect", "useRef",
      "useCallback", "useMemo", "useContext", "useReducer",
      "useLayoutEffect", "Fragment", "StrictMode", "Suspense",
      "createElement", "cloneElement", "Children", "FC", "VFC",
      "ReactNode", "ReactElement", "Key", "Ref", "Props",
      "className", "onChange", "onClick", "onSubmit", "key", "ref",
      "dangerouslySetInnerHTML", "htmlFor", "console", "Math",
      "JSON", "Promise", "Array", "Object", "String", "Number",
      "Partial", "Required", "Readonly", "Record", "Pick", "Omit",
      "Exclude", "Extract", "ReturnType", "any", "void", "never",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ["'", '"', "`"],
  },

  // ─── Web: JSON ────────────────────────────────────────────────
  json: {
    name: "JSON",
    keywords: [
      "true", "false", "null",
    ],
    builtins: [],
    commentSingle: "",
    commentMulti: ["", ""],
    stringChars: ['"'],
  },

  // ─── Web: XML ─────────────────────────────────────────────────
  xml: {
    name: "XML",
    keywords: [
      "?xml", "encoding", "version", "standalone",
      "xmlns", "xmlns:xsi", "xsi:schemaLocation",
      "xsi:noNamespaceSchemaLocation", "xsi:type",
      "element", "attribute", "complexType", "simpleType",
      "sequence", "choice", "all", "restriction", "extension",
      "enumeration", "pattern", "minLength", "maxLength",
      "minInclusive", "maxInclusive", "minExclusive",
      "maxExclusive", "length", "fractionDigits",
      "totalDigits", "whiteSpace", "import", "include",
      "redefine", "annotation", "documentation", "appinfo",
      "key", "keyref", "unique", "selector", "field",
      "group", "attributeGroup", "any", "anyAttribute",
      "list", "union", "notation", "schema", "types",
    ],
    builtins: [
      "xs:string", "xs:integer", "xs:int", "xs:long",
      "xs:short", "xs:byte", "xs:decimal", "xs:float",
      "xs:double", "xs:boolean", "xs:date", "xs:dateTime",
      "xs:time", "xs:duration", "xs:gYear", "xs:gMonth",
      "xs:gDay", "xs:gYearMonth", "xs:gMonthDay",
      "xs:hexBinary", "xs:base64Binary", "xs:anyURI",
      "xs:QName", "xs:normalizedString", "xs:token",
      "xs:language", "xs:NMTOKEN", "xs:NMTOKENS", "xs:Name",
      "xs:NCName", "xs:ID", "xs:IDREF", "xs:ENTITY",
      "xs:positiveInteger", "xs:negativeInteger",
      "xs:nonNegativeInteger", "xs:nonPositiveInteger",
      "xs:unsignedLong", "xs:unsignedInt", "xs:unsignedShort",
      "xs:unsignedByte", "xs:anyType", "xs:anySimpleType",
    ],
    commentSingle: "",
    commentMulti: ["<!--", "-->"],
    stringChars: ['"', "'"],
  },

  // ─── Web: YAML ────────────────────────────────────────────────
  yaml: {
    name: "YAML",
    keywords: [
      "true", "false", "yes", "no", "on", "off", "null", "~",
    ],
    builtins: [
      "---", "...", "!!str", "!!int", "!!float", "!!bool",
      "!!null", "!!seq", "!!map", "!!set", "!!timestamp",
      "!!binary", "!!merge", "!!value", "!!include",
      "!!python/object", "!!python/tuple",
    ],
    commentSingle: "#",
    commentMulti: ["", ""],
    stringChars: ['"', "'"],
  },

  // ─── Web: TOML ────────────────────────────────────────────────
  toml: {
    name: "TOML",
    keywords: [
      "true", "false",
    ],
    builtins: [
      "[", "]]", "[[", "]]", "=", "inline", "array",
      "string", "integer", "float", "boolean", "datetime",
      "local_datetime", "local_date", "local_time",
    ],
    commentSingle: "#",
    commentMulti: ["", ""],
    stringChars: ['"', "'"],
  },

  // ─── Web: GraphQL ─────────────────────────────────────────────
  graphql: {
    name: "GraphQL",
    keywords: [
      "type", "input", "interface", "union", "enum", "scalar",
      "extend", "implements", "schema", "query", "mutation",
      "subscription", "fragment", "on", "null", "true", "false",
      "directive", "repeatable", "list",
    ],
    builtins: [
      "Int", "Float", "String", "Boolean", "ID", "Date",
      "DateTime", "JSON", "Upload", "PageInfo", "Node",
      "Edge", "Connection", "include", "skip", "deprecated",
      "reason", "specifiedBy", "url", "Int!", "Float!",
      "String!", "Boolean!", "ID!", "[", "]",
    ],
    commentSingle: "#",
    commentMulti: ["", ""],
    stringChars: ['"', '"""'],
  },

  // ─── Web: SQL ─────────────────────────────────────────────────
  sql: {
    name: "SQL",
    keywords: [
      "SELECT", "FROM", "WHERE", "INSERT", "INTO", "VALUES",
      "UPDATE", "SET", "DELETE", "CREATE", "TABLE", "DROP",
      "ALTER", "ADD", "COLUMN", "INDEX", "VIEW", "JOIN",
      "INNER", "LEFT", "RIGHT", "OUTER", "FULL", "CROSS",
      "ON", "AND", "OR", "NOT", "IN", "BETWEEN", "LIKE",
      "IS", "NULL", "AS", "ORDER", "BY", "GROUP", "HAVING",
      "DISTINCT", "LIMIT", "OFFSET", "UNION", "ALL",
      "EXISTS", "CASE", "WHEN", "THEN", "ELSE", "END",
      "ASC", "DESC", "PRIMARY", "KEY", "FOREIGN", "REFERENCES",
      "CONSTRAINT", "DEFAULT", "CHECK", "UNIQUE", "CASCADE",
      "GRANT", "REVOKE", "BEGIN", "COMMIT", "ROLLBACK",
      "TRANSACTION", "TRIGGER", "PROCEDURE", "FUNCTION",
      "RETURN", "RETURNS", "DECLARE", "IF", "WHILE", "FOR",
      "EXPLAIN", "ANALYZE", "WITH", "RECURSIVE", "OVER",
      "PARTITION", "ROW_NUMBER", "RANK", "DENSE_RANK",
      "COALESCE", "CAST", "CONVERT", "MERGE", "USING",
      "TOP", "FETCH", "NEXT", "ROWS", "ONLY", "INTO",
    ],
    builtins: [
      "COUNT", "SUM", "AVG", "MIN", "MAX", "ABS", "CEIL",
      "FLOOR", "ROUND", "TRUNCATE", "POWER", "SQRT",
      "UPPER", "LOWER", "LENGTH", "SUBSTRING", "TRIM",
      "LTRIM", "RTRIM", "REPLACE", "CONCAT", "COALESCE",
      "NULLIF", "ISNULL", "NVL", "CURRENT_DATE",
      "CURRENT_TIME", "CURRENT_TIMESTAMP", "NOW", "DATE",
      "YEAR", "MONTH", "DAY", "HOUR", "MINUTE", "SECOND",
      "EXTRACT", "DATE_TRUNC", "DATE_ADD", "DATE_SUB",
      "DATEDIFF", "IFNULL", "IF", "CASE", "ROW_NUMBER",
      "LAG", "LEAD", "FIRST_VALUE", "LAST_VALUE",
      "ARRAY_AGG", "STRING_AGG", "JSON_EXTRACT",
      "JSON_ARRAY", "JSON_OBJECT", "BOOLEAN", "INTEGER",
      "VARCHAR", "TEXT", "DECIMAL", "FLOAT", "DOUBLE",
      "TIMESTAMP", "SERIAL", "BIGINT", "SMALLINT",
    ],
    commentSingle: "--",
    commentMulti: ["/*", "*/"],
    stringChars: ["'", '"'],
    caseInsensitive: true,
  },

  // ─── Web: Bash ────────────────────────────────────────────────
  bash: {
    name: "Bash",
    keywords: [
      "if", "then", "else", "elif", "fi", "for", "while", "until",
      "do", "done", "case", "esac", "in", "function", "select",
      "time", "coproc", "|", "||", "&&", "&", ";", ";;", ";;&",
      "export", "local", "readonly", "declare", "typeset",
      "unset", "set", "shift", "return", "exit", "break",
      "continue", "source", "alias", "unalias", "echo",
      "printf", "read", "cd", "pwd", "ls", "mkdir", "rm",
      "cp", "mv", "cat", "grep", "sed", "awk", "find",
      "sort", "uniq", "wc", "head", "tail", "cut", "tr",
      "chmod", "chown", "chgrp", "ln", "touch", "sleep",
    ],
    builtins: [
      "true", "false", "test", "[", "]]", "[[", "(( ))",
      "$?", "$!", "$$", "$#", "$@", "$*", "$0", "$1", "$2",
      "$HOME", "$PATH", "$USER", "$SHELL", "$PWD", "$OLDPWD",
      "$HOSTNAME", "$RANDOM", "$SECONDS", "$UID", "$EUID",
      "$BASH", "$BASH_VERSION", "$FUNCNAME", "$LINENO",
      "OPTARG", "OPTIND", "getopts", "eval", "exec",
      "trap", "wait", "kill", "jobs", "bg", "fg", "disown",
      "nohup", "type", "which", "command", "builtin",
      "hash", "bind", "caller", "compgen", "complete",
      "compopt", "dirs", "enable", "help", "history",
      "logout", "mapfile", "readarray", "shopt", "suspend",
    ],
    commentSingle: "#",
    commentMulti: ["", ""],
    stringChars: ["'", '"'],
  },

  // ─── Web: PowerShell ──────────────────────────────────────────
  powershell: {
    name: "PowerShell",
    keywords: [
      "if", "else", "elseif", "switch", "foreach", "for",
      "do", "while", "until", "in", "break", "continue",
      "return", "exit", "throw", "try", "catch", "finally",
      "trap", "function", "filter", "param", "begin",
      "process", "end", "dynamicparam", "class", "enum",
      "define", "using", "var", "workflow", "parallel",
      "sequence", "inlinescript", "configuration",
      "data", "foreach-object", "where-object",
    ],
    builtins: [
      "Write-Host", "Write-Output", "Write-Error",
      "Write-Warning", "Write-Verbose", "Write-Debug",
      "Write-Information", "Get-Command", "Get-Help",
      "Get-Member", "Get-ChildItem", "Get-Content",
      "Get-Process", "Get-Service", "Get-EventLog",
      "Set-Content", "Set-Item", "Set-Location",
      "New-Object", "New-Item", "Remove-Item",
      "Copy-Item", "Move-Item", "Invoke-Command",
      "Invoke-Expression", "Invoke-WebRequest",
      "Select-Object", "Where-Object", "ForEach-Object",
      "Sort-Object", "Group-Object", "Measure-Object",
      "Format-Table", "Format-List", "ConvertTo-Json",
      "ConvertFrom-Json", "ConvertTo-CSV",
      "ConvertFrom-CSV", "Import-Module", "Export-Module",
      "Test-Path", "Join-Path", "Split-Path",
      "$true", "$false", "$null", "$this", "$_",
      "$input", "$args", "$PSItem", "$PSScriptRoot",
      "$PWD", "$env", "$Error", "$Matches", "$LastExitCode",
    ],
    commentSingle: "#",
    commentMulti: ["<#", "#>"],
    stringChars: ["'", '"'],
  },

  // ─── Systems: C ───────────────────────────────────────────────
  c: {
    name: "C",
    keywords: [
      "auto", "break", "case", "char", "const", "continue",
      "default", "do", "double", "else", "enum", "extern",
      "float", "for", "goto", "if", "inline", "int", "long",
      "register", "restrict", "return", "short", "signed",
      "sizeof", "static", "struct", "switch", "typedef",
      "union", "unsigned", "void", "volatile", "while",
      "_Alignas", "_Alignof", "_Atomic", "_Bool", "_Complex",
      "_Generic", "_Imaginary", "_Noreturn", "_Static_assert",
      "_Thread_local",
    ],
    builtins: [
      "printf", "fprintf", "sprintf", "snprintf", "scanf",
      "fscanf", "sscanf", "puts", "fputs", "fgets", "gets",
      "getchar", "putchar", "malloc", "calloc", "realloc",
      "free", "memcpy", "memmove", "memset", "memcmp",
      "strlen", "strcpy", "strncpy", "strcat", "strncat",
      "strcmp", "strncmp", " strchr", "strrchr", "strstr",
      "strtok", "atoi", "atol", "atof", "strtol", "strtoul",
      "strtod", "abort", "exit", "atexit", "atoi",
      "fopen", "fclose", "fread", "fwrite", "fseek",
      "ftell", "rewind", "feof", "ferror", "fflush",
      "assert", "offsetof", "sizeof", "NULL", "EOF",
      "FILE", "size_t", "ptrdiff_t", "intptr_t", "uintptr_t",
      "int8_t", "int16_t", "int32_t", "int64_t", "uint8_t",
      "UINT16_MAX", "INT32_MIN", "INT32_MAX", "SIZE_MAX",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Systems: C++ ─────────────────────────────────────────────
  cpp: {
    name: "C++",
    keywords: [
      "alignas", "alignof", "and", "and_eq", "asm", "auto",
      "bitand", "bitor", "bool", "break", "case", "catch",
      "char", "char8_t", "char16_t", "char32_t", "class",
      "compl", "concept", "const", "consteval", "constexpr",
      "constinit", "const_cast", "continue", "co_await",
      "co_return", "co_yield", "decltype", "default", "delete",
      "do", "double", "dynamic_cast", "else", "enum", "explicit",
      "export", "extern", "false", "float", "for", "friend",
      "goto", "if", "inline", "int", "long", "mutable",
      "namespace", "new", "noexcept", "not", "not_eq", "nullptr",
      "operator", "or", "or_eq", "private", "protected", "public",
      "register", "reinterpret_cast", "requires", "return",
      "short", "signed", "sizeof", "static", "static_assert",
      "static_cast", "struct", "switch", "template", "this",
      "thread_local", "throw", "true", "try", "typedef",
      "typeid", "typename", "union", "unsigned", "using",
      "virtual", "void", "volatile", "while", "xor", "xor_eq",
      "override", "final",
    ],
    builtins: [
      "std", "cout", "cin", "cerr", "clog", "endl", "string",
      "vector", "map", "set", "unordered_map", "unordered_set",
      "pair", "tuple", "array", "deque", "list", "queue",
      "stack", "priority_queue", "bitset", "optional",
      "variant", "any", "shared_ptr", "unique_ptr", "weak_ptr",
      "make_shared", "make_unique", "make_pair", "make_tuple",
      "size_t", "int64_t", "uint64_t", "INT32_MAX",
      "std::move", "std::forward", "std::sort", "std::find",
      "std::transform", "std::copy", "std::accumulate",
      "std::min", "std::max", "std::clamp", "std::swap",
      "std::begin", "std::end", "std::cout", "std::cin",
      "std::endl", "std::mutex", "std::thread", "std::async",
      "std::future", "std::promise", "std::condition_variable",
      "printf", "fprintf", "scanf", "malloc", "free",
      "NULL", "nullptr", "EOF", "SIZE_MAX",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Systems: C# ──────────────────────────────────────────────
  csharp: {
    name: "C#",
    keywords: [
      "abstract", "as", "base", "bool", "break", "byte", "case",
      "catch", "char", "checked", "class", "const", "continue",
      "decimal", "default", "delegate", "do", "double", "else",
      "enum", "event", "explicit", "extern", "false", "finally",
      "fixed", "float", "for", "foreach", "goto", "if", "implicit",
      "in", "int", "interface", "internal", "is", "lock", "long",
      "namespace", "new", "null", "object", "operator", "out",
      "override", "params", "private", "protected", "public",
      "readonly", "ref", "return", "sbyte", "sealed", "short",
      "sizeof", "stackalloc", "static", "string", "struct",
      "switch", "this", "throw", "true", "try", "typeof",
      "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
      "var", "virtual", "void", "volatile", "while", "async",
      "await", "dynamic", "global", "nint", "nuint", "record",
      "required", "scoped", "with", "when", "and", "or", "not",
      "init", "file", "get", "set",
    ],
    builtins: [
      "Console", "WriteLine", "ReadLine", "Convert",
      "Math", "String", "Int32", "Int64", "Double", "Float",
      "Boolean", "DateTime", "TimeSpan", "Guid", "Exception",
      "ArgumentException", "InvalidOperationException",
      "List", "Dictionary", "HashSet", "Queue", "Stack",
      "Task", "Task", "LINQ", "IEnumerable", "IEnumerable",
      "Action", "Func", "Predicate", "Comparison",
      "Array", "ArrayList", "Hashtable", "SortedList",
      "StringBuilder", "Regex", "Match", "Group",
      "File", "Directory", "Path", "StreamReader", "StreamWriter",
      "HttpClient", "HttpRequestMessage", "HttpResponseMessage",
      "Thread", "Mutex", "Semaphore", "Monitor",
      "Environment", "GC", "Type", "Activator", "Attribute",
      "Nullable", "ValueTask", "Span", "ReadOnlySpan",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Systems: Go ──────────────────────────────────────────────
  go: {
    name: "Go",
    keywords: [
      "break", "case", "chan", "const", "continue", "default",
      "defer", "else", "fallthrough", "for", "func", "go",
      "goto", "if", "import", "interface", "map", "package",
      "range", "return", "select", "struct", "switch", "type",
      "var",
    ],
    builtins: [
      "append", "cap", "close", "copy", "delete", "len",
      "make", "new", "panic", "print", "println", "recover",
      "complex", "real", "imag", "error", "true", "false",
      "nil", "iota", "string", "int", "int8", "int16",
      "int32", "int64", "uint", "uint8", "uint16", "uint32",
      "uint64", "float32", "float64", "complex64",
      "complex128", "byte", "rune", "uintptr", "bool",
      "fmt", "Println", "Printf", "Sprintf", "Errorf",
      "os", "File", "Open", "Create", "ReadFile",
      "WriteFile", "Args", "Stdin", "Stdout", "Stderr",
      "log", "Fatal", "Fatalf", "Println", "Printf",
      "net", "http", "HandleFunc", "ListenAndServe",
      "json", "Marshal", "Unmarshal", "Encoder",
      "Decoder", "NewEncoder", "time", "Now", "Duration",
      "Sleep", "Parse", "Format", "sync", "Mutex",
      "RWMutex", "WaitGroup", "context", "Background",
      "TODO", "WithCancel", "WithTimeout", "strings",
      "Contains", "HasPrefix", "HasSuffix", "Split",
      "Join", "Replace", "ToUpper", "ToLower", "TrimSpace",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'", "`"],
  },

  // ─── Systems: Rust ────────────────────────────────────────────
  rust: {
    name: "Rust",
    keywords: [
      "as", "async", "await", "break", "const", "continue",
      "crate", "dyn", "else", "enum", "extern", "fn", "for",
      "if", "impl", "in", "let", "loop", "match", "mod",
      "move", "mut", "pub", "ref", "return", "self", "Self",
      "static", "struct", "super", "trait", "type", "unsafe",
      "use", "where", "while", "yield",
    ],
    builtins: [
      "bool", "char", "f32", "f64", "i8", "i16", "i32", "i64",
      "i128", "isize", "str", "u8", "u16", "u32", "u64", "u128",
      "usize", "String", "Vec", "Box", "Rc", "Arc", "Option",
      "Some", "None", "Result", "Ok", "Err", "HashMap",
      "HashSet", "BTreeMap", "BTreeSet", "BinaryHeap",
      "LinkedList", "VecDeque", "Cow", "Cell", "RefCell",
      "Mutex", "RwLock", "Condvar", "Barrier", "Once",
      "AtomicBool", "AtomicUsize", "AtomicIsize",
      "println", "eprintln", "format", "dbg", "todo",
      "unimplemented", "unreachable", "panic",
      "assert", "assert_eq", "assert_ne", "debug_assert",
      "clone", "copy", "default", "drop", "Send", "Sync",
      "Iterator", "IntoIterator", "From", "Into", "TryFrom",
      "TryInto", "AsRef", "AsMut", "Borrow", "BorrowMut",
      "ToOwned", "ToString", "FromStr", "Display", "Debug",
      "Serialize", "Deserialize", "Clone", "Copy", "Eq",
      "PartialEq", "Ord", "PartialOrd", "Hash", "Drop",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"'],
  },

  // ─── Systems: Swift ───────────────────────────────────────────
  swift: {
    name: "Swift",
    keywords: [
      "associatedtype", "class", "deinit", "enum", "extension",
      "fileprivate", "func", "import", "init", "inout",
      "internal", "let", "open", "operator", "private",
      "precedencegroup", "protocol", "public", "rethrows",
      "static", "struct", "subscript", "typealias", "var",
      "break", "case", "catch", "continue", "default", "defer",
      "do", "else", "fallthrough", "for", "guard", "if",
      "in", "repeat", "return", "switch", "throw", "try",
      "where", "while", "as", "Any", "catch", "false",
      "is", "nil", "rethrows", "self", "Self", "super",
      "throw", "throws", "true", "try", "async", "await",
      "actor", "some", "any", "in", "typealias", "borrowing",
      "consuming", "sending", "isolated", "nonisolated",
    ],
    builtins: [
      "Array", "Dictionary", "Set", "String", "Character",
      "Int", "Int8", "Int16", "Int32", "Int64", "UInt",
      "UInt8", "UInt16", "UInt32", "UInt64", "Float",
      "Double", "Bool", "Optional", "Result", "Range",
      "ClosedRange", "Stride", "Tuple", "Void", "Never",
      "print", "dump", "debugPrint", "assert", "assertionFailure",
      "precondition", "fatalError", "min", "max", "abs",
      "sort", "map", "filter", "reduce", "flatMap",
      "compactMap", "forEach", "contains", "firstIndex",
      "lastIndex", "remove", "insert", "append", "pop",
      "reversed", "sorted", "shuffled", "count", "isEmpty",
      "description", "hashValue", "Equatable", "Hashable",
      "Codable", "Encodable", "Decodable", "Comparable",
      "CustomStringConvertible", "CustomDebugStringConvertible",
      "Error", "Sequence", "Collection", "MutableCollection",
      "RandomAccessCollection", "IteratorProtocol", "Hasher",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"'],
  },

  // ─── Systems: Kotlin ──────────────────────────────────────────
  kotlin: {
    name: "Kotlin",
    keywords: [
      "package", "as", "typealias", "class", "interface",
      "this", "super", "val", "var", "fun", "for", "do",
      "while", "if", "when", "try", "throw", "return",
      "break", "continue", "object", "companion", "init",
      "sealed", "data", "inner", "enum", "annotation",
      " typealias", "type", "by", "constructor", "dynamic",
      "import", "is", "in", "!is", "!in", "as?", "suspend",
      "inline", "noinline", "crossinline", "reified",
      "tailrec", "operator", "infix", "external",
      "override", "abstract", "final", "open", "private",
      "protected", "public", "internal", "lateinit",
      "vararg", "out", "catch", "finally", "it",
      "field", "property", "receiver", "param", "setparam",
      "delegate",
    ],
    builtins: [
      "Int", "Long", "Short", "Byte", "Double", "Float",
      "Boolean", "Char", "String", "Unit", "Nothing",
      "Any", "Array", "List", "MutableList", "Set",
      "MutableSet", "Map", "MutableMap", "Pair", "Triple",
      "lazy", "println", "print", "readLine", "readln",
      "toInt", "toLong", "toDouble", "toFloat", "toString",
      "toBoolean", "toIntOrNull", "toLongOrNull",
      "also", "apply", "let", "run", "with", "takeIf",
      "takeUnless", "repeat", "require", "check", "error",
      "TODO", "assertTrue", "assertEquals", "map", "filter",
      "reduce", "fold", "flatMap", "forEach", "count",
      "firstOrNull", "lastOrNull", "find", "associate",
      "groupBy", "sorted", "reversed", "distinct",
      "sumOf", "minOf", "maxOf", "average", "minOrNull",
      "maxOrNull", "nullable", "sequence", "generateSequence",
      "coroutineScope", "launch", "async", "withContext",
      "Flow", "collect", "emit",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Systems: Java ────────────────────────────────────────────
  java: {
    name: "Java",
    keywords: [
      "abstract", "assert", "boolean", "break", "byte", "case",
      "catch", "char", "class", "const", "continue", "default",
      "do", "double", "else", "enum", "extends", "final",
      "finally", "float", "for", "goto", "if", "implements",
      "import", "instanceof", "int", "interface", "long",
      "native", "new", "package", "private", "protected",
      "public", "return", "short", "static", "strictfp",
      "super", "switch", "synchronized", "this", "throw",
      "throws", "transient", "try", "void", "volatile",
      "while", "true", "false", "null", "record", "sealed",
      "permits", "var", "yield", "module", "requires",
      "exports", "opens", "to", "transitive", "uses", "provides",
      "with",
    ],
    builtins: [
      "System", "out", "println", "print", "err", "exit",
      "String", "Integer", "Long", "Double", "Float",
      "Boolean", "Character", "Byte", "Short", "Object",
      "Class", "Thread", "Runnable", "Exception",
      "RuntimeException", "NullPointerException",
      "IllegalArgumentException", "IndexOutOfBoundsException",
      "ArrayList", "LinkedList", "HashMap", "HashSet",
      "TreeMap", "TreeSet", "LinkedHashMap", "PriorityQueue",
      "Arrays", "Collections", "List", "Set", "Map",
      "Queue", "Deque", "Iterator", "Comparator", "Optional",
      "Stream", "OptionalInt", "OptionalLong", "Math",
      "StringBuffer", "StringBuilder", "Scanner", "File",
      "FileReader", "FileWriter", "BufferedReader",
      "BufferedWriter", "InputStreamReader",
      "OutputStreamWriter", "FileInputStream",
      "FileOutputStream", "Pattern", "Matcher", "Regex",
      "BigInteger", "BigDecimal", "Date", "Calendar",
      "SimpleDateFormat", "UUID", "Random", "ThreadLocal",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Systems: Scala ───────────────────────────────────────────
  scala: {
    name: "Scala",
    keywords: [
      "abstract", "case", "catch", "class", "def", "do",
      "else", "extends", "false", "final", "finally",
      "for", "forSome", "if", "implicit", "import", "lazy",
      "match", "new", "null", "object", "override", "package",
      "private", "protected", "return", "sealed", "super",
      "this", "throw", "trait", "true", "try", "type",
      "val", "var", "while", "with", "yield",
      "given", "using", "enum", "then", "end", "extension",
      "opaque", "open", "transparent", "inline", "def",
      "export", "macro",
    ],
    builtins: [
      "Int", "Long", "Short", "Byte", "Double", "Float",
      "Boolean", "Char", "String", "Unit", "Nothing",
      "Any", "AnyRef", "AnyVal", "List", "Nil", "Cons",
      "Map", "Set", "Option", "Some", "None", "Either",
      "Left", "Right", "Try", "Success", "Failure",
      "Future", "Promise", "Vector", "Array", "Seq",
      "IndexedSeq", "Range", "Tuple", "Pair", "Triple",
      "println", "print", "readLine", "require", "assert",
      "Predef", "BigInt", "BigDecimal", "Regex",
      "scala.util", "scala.collection", "scala.concurrent",
      "scala.math", "scala.io", "scala.xml", "DateTime",
      "Duration", "TimeoutException", "ExecutionContext",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Systems: Ruby ────────────────────────────────────────────
  ruby: {
    name: "Ruby",
    keywords: [
      "alias", "and", "begin", "break", "case", "class",
      "def", "defined", "do", "else", "elsif", "end",
      "ensure", "for", "if", "in", "module", "next", "nil",
      "not", "or", "redo", "rescue", "retry", "return",
      "self", "super", "then", "true", "undef", "unless",
      "until", "when", "while", "yield", "__FILE__",
      "__LINE__", "__ENCODING__", "BEGIN", "END",
    ],
    builtins: [
      "puts", "print", "p", "gets", "chomp", "chop",
      "to_s", "to_i", "to_f", "to_a", "to_h", "to_sym",
      "length", "size", "each", "map", "collect", "select",
      "reject", "find", "detect", "grep", "inject",
      "reduce", "sort", "reverse", "flatten", "compact",
      "uniq", "zip", "include", "respond_to", "is_a",
      "kind_of", "nil", "empty", "blank", "present",
      "require", "require_relative", "load", "include",
      "extend", "attr_reader", "attr_writer", "attr_accessor",
      "raise", "catch", "throw", "lambda", "proc",
      "class_eval", "instance_eval", "define_method",
      "method_missing", "send", "public_send",
      "Array", "Hash", "String", "Integer", "Float",
      "Symbol", "Regexp", "Range", "Proc", "Lambda",
      "File", "Dir", "IO", "Time", "Date", "DateTime",
      "OpenStruct", "Struct", "Enumerable", "Comparable",
    ],
    commentSingle: "#",
    commentMulti: ["=begin", "=end"],
    stringChars: ['"', "'", '`'],
  },

  // ─── Systems: Python ──────────────────────────────────────────
  python: {
    name: "Python",
    keywords: [
      "False", "None", "True", "and", "as", "assert",
      "async", "await", "break", "class", "continue",
      "def", "del", "elif", "else", "except", "finally",
      "for", "from", "global", "if", "import", "in",
      "is", "lambda", "nonlocal", "not", "or", "pass",
      "raise", "return", "try", "while", "with", "yield",
      "match", "case", "type", "walrus",
    ],
    builtins: [
      "print", "len", "range", "input", "int", "float",
      "str", "bool", "list", "dict", "set", "tuple",
      "frozenset", "bytes", "bytearray", "complex",
      "enumerate", "zip", "map", "filter", "reduce",
      "sorted", "reversed", "any", "all", "min", "max",
      "sum", "abs", "round", "pow", "divmod", "ord",
      "chr", "bin", "hex", "oct", "id", "type", "isinstance",
      "issubclass", "hasattr", "getattr", "setattr",
      "delattr", "vars", "dir", "help", "repr", "hash",
      "callable", "iter", "next", "property", "staticmethod",
      "classmethod", "super", "object", "Exception",
      "ValueError", "TypeError", "KeyError", "IndexError",
      "AttributeError", "RuntimeError", "StopIteration",
      "NotImplementedError", "ImportError", "OSError",
      "FileNotFoundError", "open", "format", "breakpoint",
      "ascii", "compile", "eval", "exec", "globals",
      "locals", "memoryview", "slice", "copyright",
      "credits", "license", "quit", "exit",
    ],
    commentSingle: "#",
    commentMulti: ["", ""],
    stringChars: ['"', "'", '"""', "'''"],
  },

  // ─── Functional: Haskell ──────────────────────────────────────
  haskell: {
    name: "Haskell",
    keywords: [
      "case", "class", "data", "default", "deriving", "do",
      "else", "if", "import", "in", "infixl", "infixr",
      "infix", "instance", "let", "module", "newtype",
      "of", "then", "type", "where", "qualified", "as",
      "hiding", "forall", "family", "pattern",
    ],
    builtins: [
      "Int", "Integer", "Float", "Double", "Char", "String",
      "Bool", "Maybe", "Just", "Nothing", "Either", "Left",
      "Right", "Ordering", "LT", "EQ", "GT", "IO", "IORef",
      "List", "Map", "Set", "Show", "Read", "Eq", "Ord",
      "Enum", "Bounded", "Num", "Real", "Integral",
      "Fractional", "RealFrac", "Floating", "RealFloat",
      "putStrLn", "putStr", "print", "getLine", "getChar",
      "read", "readLn", "show", "read", "not", "mod",
      "div", "rem", "quot", "even", "odd", "gcd", "lcm",
      "succ", "pred", "toEnum", "fromEnum", "minBound",
      "maxBound", "map", "filter", "foldl", "foldr",
      "scanl", "scanr", "zip", "unzip", "zipWith",
      "head", "tail", "init", "last", "null", "length",
      "take", "drop", "splitAt", "takeWhile", "dropWhile",
      "span", "break", "elem", "notElem", "lookup",
      "concat", "concatMap", "reverse", "and", "or",
      "any", "all", "sum", "product", "maximum", "minimum",
      "sort", "nub", "union", "intersect", "sortOn",
      "fst", "snd", "curry", "uncurry", "id", "const",
      "flip", "until", "error", "undefined",
    ],
    commentSingle: "--",
    commentMulti: ["{-", "-}"],
    stringChars: ['"', "'"],
  },

  // ─── Functional: Elixir ───────────────────────────────────────
  elixir: {
    name: "Elixir",
    keywords: [
      "alias", "case", "cond", "def", "defp", "defmodule",
      "defmacro", "defmacrop", "do", "else", "end", "fn",
      "for", "if", "import", "quote", "require", "try",
      "unless", "use", "with", "raise", "rescue", "catch",
      "after", "when", "and", "or", "not", "in", "true",
      "false", "nil",
    ],
    builtins: [
      "IO", "puts", "inspect", "gets", "read", "write",
      "Kernel", "length", "size", "first", "last", "hd",
      "tl", "Enum", "map", "filter", "reduce", "each",
      "sort", "uniq", "flat_map", "count", "any", "all",
      "at", "fetch", "member", "max", "min", "sum",
      "product", "chunk_every", "chunk_by", "group_by",
      "split_with", "to_list", "List", "foldl", "foldr",
      "zip", "unzip", "flatten", "reverse", "Map", "get",
      "put", "update", "delete", "merge", "keys", "values",
      "has_key", "String", "split", "trim", "upcase",
      "downcase", "replace", "contains", "starts_with",
      "ends_with", "match", "Regex", "Atom", "to_string",
      "Tuple", "elem", "put_elem", "append_elem",
      "Integer", "Float", "is_integer", "is_float",
      "is_binary", "is_list", "is_map", "is_tuple",
      "is_atom", "is_nil", "is_boolean", "is_function",
      "is_pid", "is_port", "is_reference", "self", "send",
      "spawn", "spawn_link", "receive", "Node", "Process",
      "Agent", "Task", "GenServer", "Supervisor",
    ],
    commentSingle: "#",
    commentMulti: ["", ""],
    stringChars: ['"', "'"],
  },

  // ─── Functional: Erlang ───────────────────────────────────────
  erlang: {
    name: "Erlang",
    keywords: [
      "after", "begin", "case", "catch", "cond", "end",
      "fun", "if", "let", "of", "receive", "try", "when",
      "andalso", "orelse", "not", "and", "or", "xor",
      "band", "bor", "bxor", "bnot", "bsl", "bsr",
      "div", "rem",
    ],
    builtins: [
      "module", "export", "import", "behaviour",
      "behaviour_info", "spec", "type", "record", "define",
      "include", "include_lib", "ifdef", "ifndef", "else",
      "endif", "file", "ok", "error", "true", "false",
      "undefined", "io", "format", "fwrite", "put_chars",
      "get_line", "lists", "map", "filter", "foldl",
      "foldr", "foreach", "sort", "reverse", "flatten",
      "nth", "append", "concat", "subtract", "merge",
      "usort", "keyfind", "keysort", "unzip", "zip",
      "seq", "foreach", "sum", "max", "min", "erlang",
      "spawn", "spawn_link", "spawn_monitor", "send",
      "receive", "self", "register", "unregister",
      "whereis", "process_info", "exit", "link", "unlink",
      "monitor", "demonitor", "atom_to_list",
      "list_to_atom", "integer_to_list",
      "list_to_integer", "float", "round", "trunc", "abs",
      "tuple_size", "element", "setelement", "size",
      "length", "byte_size", "bit_size", "binary_to_list",
      "list_to_binary", "binary_part", "is_atom",
      "is_integer", "is_float", "is_list", "is_tuple",
      "is_binary", "is_boolean", "is_function",
      "is_pid", "is_port", "is_reference", "is_map",
    ],
    commentSingle: "%",
    commentMulti: ["", ""],
    stringChars: ['"'],
  },

  // ─── Functional: Clojure ──────────────────────────────────────
  clojure: {
    name: "Clojure",
    keywords: [
      "def", "defn", "defn-", "defmacro", "defmulti",
      "defmethod", "defprotocol", "defrecord", "defstruct",
      "deftype", "defonce", "defn-", "let", "letfn",
      "binding", "loop", "recur", "if", "if-not", "if-let",
      "if-some", "when", "when-not", "when-let", "when-some",
      "cond", "condp", "case", "do", "doseq", "dotimes",
      "for", "while", "try", "catch", "finally", "throw",
      "fn", "defn", "ns", "require", "use", "import",
      "refer", "rename", "exclude", "only",
    ],
    builtins: [
      "nil", "true", "false", "print", "println", "pr",
      "prn", "str", "format", "printf", "newline", "flush",
      "read", "read-line", "read-string", "slurp", "spit",
      "first", "rest", "last", "nth", "cons", "conj",
      "assoc", "dissoc", "get", "contains", "find",
      "keys", "vals", "merge", "select-keys", "update",
      "update-in", "assoc-in", "get-in", "map", "filter",
      "reduce", "reduce-kv", "into", "take", "drop",
      "take-while", "drop-while", "sort", "sort-by",
      "reverse", "flatten", "distinct", "group-by",
      "partition", "partition-all", "partition-by",
      "frequencies", "count", "empty", "every", "some",
      "not-any", "not-every", "apply", "partial",
      "comp", "complement", "identity", "constantly",
      "juxt", "pipeline", "thread-first", "thread-last",
      "atom", "swap", "reset", "compare-and-set",
      "deref", "future", "promise", "deliver",
      "delay", "force", "realized", "with-open",
      "with-precision", "with-in-str", "with-out-str",
    ],
    commentSingle: ";;",
    commentMulti: ["", ""],
    stringChars: ['"'],
  },

  // ─── Data: R ──────────────────────────────────────────────────
  r: {
    name: "R",
    keywords: [
      "if", "else", "repeat", "while", "function", "for",
      "in", "next", "break", "TRUE", "FALSE", "NULL",
      "Inf", "NaN", "NA", "NA_integer", "NA_real",
      "NA_complex", "NA_character", "return", "library",
      "require", "source", "local",
    ],
    builtins: [
      "print", "cat", "sprintf", "paste", "paste0",
      "str", "summary", "head", "tail", "View", "dim",
      "nrow", "ncol", "length", "names", "rownames",
      "colnames", "class", "typeof", "is.numeric",
      "is.character", "is.logical", "is.factor",
      "is.integer", "is.double", "is.vector", "is.list",
      "is.data.frame", "is.matrix", "is.array",
      "is.function", "is.null", "is.na", "is.nan",
      "is.finite", "is.infinite", "c", "vector", "list",
      "matrix", "array", "data.frame", "factor", "as.numeric",
      "as.character", "as.integer", "as.double", "as.logical",
      "as.factor", "as.data.frame", "as.matrix", "as.vector",
      "as.list", "read.csv", "read.table", "readRDS",
      "write.csv", "write.table", "saveRDS", "save",
      "load", "mean", "median", "sd", "var", "min", "max",
      "range", "sum", "prod", "abs", "sqrt", "log", "exp",
      "round", "ceiling", "floor", "trunc", "sin", "cos",
      "tan", "seq", "seq_len", "seq_along", "rep",
      "sample", "which", "which.min", "which.max",
      "order", "sort", "rank", "table", "unique",
      "duplicated", "tapply", "apply", "lapply", "sapply",
      "vapply", "mapply", "aggregate", "by", "merge",
      "rbind", "cbind", "subset", "transform", "ggplot",
      "aes", "geom_point", "geom_line", "geom_bar",
      "geom_histogram", "theme", "labs", "facet_wrap",
    ],
    commentSingle: "#",
    commentMulti: ["", ""],
    stringChars: ['"', "'"],
  },

  // ─── Data: MATLAB ─────────────────────────────────────────────
  matlab: {
    name: "MATLAB",
    keywords: [
      "break", "case", "catch", "classdef", "continue",
      "else", "elseif", "end", "for", "function", "global",
      "if", "otherwise", "parfor", "persistent", "return",
      "spmd", "switch", "try", "while",
    ],
    builtins: [
      "true", "false", "nan", "inf", "pi", "eps", "i", "j",
      "disp", "fprintf", "sprintf", "input", "keyboard",
      "error", "warning", "pause", "waitfor",
      "zeros", "ones", "eye", "rand", "randn", "randi",
      "linspace", "logspace", "colon", "meshgrid",
      "size", "length", "numel", "ndims", "isempty",
      "isequal", "isnumeric", "ischar", "isstring",
      "islogical", "iscell", "isstruct", "isfield",
      "isfinite", "isinf", "isnan", "class", "typeof",
      "double", "single", "int8", "int16", "int32",
      "int64", "uint8", "uint16", "uint32", "uint64",
      "char", "string", "cell", "struct", "table",
      "array2table", "table2array", "cell2mat", "mat2cell",
      "num2str", "str2num", "str2double", "int2str",
      "sprintf", "sscanf", "strcmp", "strcmpi", "contains",
      "startsWith", "endsWith", "strcat", "strjoin",
      "split", "strsplit", "replace", "upper", "lower",
      "abs", "sqrt", "exp", "log", "log2", "log10",
      "sin", "cos", "tan", "asin", "acos", "atan",
      "max", "min", "mean", "median", "std", "var",
      "sort", "sum", "prod", "cumsum", "cumprod",
      "diff", "gradient", "trapz", "interp1", "interp2",
      "plot", "scatter", "bar", "histogram", "imagesc",
      "imshow", "figure", "subplot", "legend", "title",
      "xlabel", "ylabel", "grid", "hold", "axis",
    ],
    commentSingle: "%",
    commentMulti: ["%{", "%}"],
    stringChars: ['"', "'"],
  },

  // ─── Data: Julia ──────────────────────────────────────────────
  julia: {
    name: "Julia",
    keywords: [
      "begin", "while", "for", "in", "if", "else",
      "elseif", "end", "try", "catch", "finally",
      "return", "function", "macro", "quote", "let",
      "local", "global", "const", "do", "struct",
      "mutable", "abstract", "type", "using", "import",
      "export", "module", "baremodule", "true", "false",
      "nothing", "missing",
    ],
    builtins: [
      "println", "print", "show", "display", "dump",
      "string", "repr", "parse", "Meta", "eval",
      "Int8", "Int16", "Int32", "Int64", "Int128",
      "UInt8", "UInt16", "UInt32", "UInt64", "UInt128",
      "Float16", "Float32", "Float64", "Bool", "Char",
      "String", "SubString", "Symbol", "Regex",
      "Range", "UnitRange", "StepRange", "LinRange",
      "Array", "Vector", "Matrix", "Tuple", "NamedTuple",
      "Dict", "Set", "Pair", "Nothing", "Some", "Any",
      "push", "pushfirst", "pop", "popfirst", "append",
      "prepend", "insert", "deleteat", "splice",
      "length", "size", "ndims", "isempty", "first",
      "last", "eachindex", "axes", "eltype", "typeof",
      "isa", "isnothing", "ismissing", "collect",
      "map", "map!", "filter", "filter!", "reduce",
      "foldl", "foldr", "foreach", "findall", "findfirst",
      "findlast", "count", "any", "all", "sum", "prod",
      "maximum", "minimum", "argmax", "argmin", "extrema",
      "sort", "sort!", "sortperm", "unique", "reverse",
      "copy", "deepcopy", "zeros", "ones", "trues",
      "falses", "fill", "rand", "randn", "range",
      "LinRange", "collect", "sqrt", "abs", "sin", "cos",
      "exp", "log", "log2", "log10", "round", "floor",
      "ceil", "clamp", "min", "max", "minmax",
      "open", "read", "write", "close", "readline",
      "eachline", "stdout", "stderr", "stdin",
    ],
    commentSingle: "#",
    commentMulti: ["#=", "=#"],
    stringChars: ['"', "'"],
  },

  // ─── Data: Fortran ────────────────────────────────────────────
  fortran: {
    name: "Fortran",
    keywords: [
      "program", "end", "function", "subroutine", "call",
      "return", "stop", "go", "to", "goto", "if", "then",
      "else", "else", "if", "end", "if", "do", "end", "do",
      "while", "cycle", "exit", "select", "case", "case",
      "default", "end", "select", "use", "only", "implicit",
      "none", "parameter", "integer", "real", "double",
      "precision", "complex", "logical", "character",
      "type", "end", "type", "module", "end", "module",
      "contains", "interface", "end", "interface",
      "allocatable", "dimension", "target", "pointer",
      "intent", "in", "out", "inout", "optional",
      "recursive", "pure", "elemental", "result", "where",
      "elsewhere", "endwhere", "forall", "associate",
      "block", "endblock", "enum", "enumerator", "null",
      "true", "false", "class", "extends", "abstract",
      "procedure", "generic", "final", "allocatable",
      "deallocate", "allocate", "stat", "allocate",
      "data", "common", "equivalence", "save",
    ],
    builtins: [
      "sin", "cos", "tan", "asin", "acos", "atan",
      "atan2", "sinh", "cosh", "tanh", "exp", "log",
      "log10", "sqrt", "abs", "int", "real", "nint",
      "anint", "mod", "modulo", "sign", "max", "min",
      "aimag", "conjg", "cmplx", "len", "len_trim",
      "trim", "adjustl", "adjustr", "index", "scan",
      "verify", "char", "ichar", "achar", "iachar",
      "present", "allocated", "associated", "kind",
      "selected_int_kind", "selected_real_kind",
      "huge", "tiny", "epsilon", "precision", "range",
      "digits", "radix", "nearest", "spacing",
      "shape", "size", "ubound", "lbound", "reshape",
      "transpose", "matmul", "dot_product", "sum",
      "product", "maxval", "minval", "count", "any",
      "all", "maxloc", "minloc", "pack", "unpack",
      "merge", "transfer", "spread", "repeat",
      "open", "close", "read", "write", "print",
      "format", " rewind", "backspace", "endfile",
      "inquire", "flush", "new_unit", "unit",
    ],
    commentSingle: "!",
    commentMulti: ["", ""],
    stringChars: ['"', "'"],
    caseInsensitive: true,
  },

  // ─── Scripting: Perl ──────────────────────────────────────────
  perl: {
    name: "Perl",
    keywords: [
      "if", "else", "elsif", "unless", "until", "while",
      "for", "foreach", "do", "given", "when", "default",
      "continue", "exit", "die", "warn", "eval", "BEGIN",
      "END", "CHECK", "INIT", "UNITCHECK", "sub", "my",
      "our", "local", "state", "return", "require", "use",
      "package", "class", "method", "field", "role",
      "extends", "has", "with",
    ],
    builtins: [
      "print", "say", "printf", "sprintf", "chomp",
      "chop", "length", "substr", "index", "rindex",
      "lc", "uc", "lcfirst", "ucfirst", "reverse",
      "split", "join", "sort", "grep", "map", "scalar",
      "undef", "defined", "delete", "exists", "keys",
      "values", "each", "push", "pop", "shift", "unshift",
      "splice", "scalar", "int", "abs", "sqrt", "exp",
      "log", "sin", "cos", "rand", "srand", "hex", "oct",
      "open", "close", "read", "write", "readline",
      "getc", "seek", "tell", "eof", "fileno",
      "binmode", "opendir", "closedir", "readdir",
      "glob", "rename", "unlink", "mkdir", "rmdir",
      "chmod", "chown", "stat", "lstat", "utime",
      "caller", "wantarray", "ref", "bless", "tie",
      "untie", "tied", "isa", "can", "VERSION",
      "__FILE__", "__LINE__", "__PACKAGE__", "__SUB__",
      "@ARGV", "@_", "$0", "$!", "$@", "$?", "$>",
      "$<", "$$", "STDIN", "STDOUT", "STDERR", "ARGV",
      "DATA", "ENV", "SIG",
    ],
    commentSingle: "#",
    commentMulti: ["=pod", "=cut"],
    stringChars: ['"', "'"],
  },

  // ─── Scripting: PHP ───────────────────────────────────────────
  php: {
    name: "PHP",
    keywords: [
      "abstract", "and", "array", "as", "break", "callable",
      "case", "catch", "class", "clone", "const", "continue",
      "declare", "default", "die", "do", "echo", "else",
      "elseif", "empty", "enddeclare", "endfor", "endforeach",
      "endif", "endswitch", "endwhile", "eval", "exit",
      "extends", "final", "finally", "fn", "for", "foreach",
      "function", "global", "goto", "if", "implements",
      "include", "include_once", "instanceof", "insteadof",
      "interface", "isset", "list", "match", "namespace",
      "new", "or", "print", "private", "protected", "public",
      "require", "require_once", "return", "static",
      "switch", "throw", "trait", "try", "unset", "use",
      "var", "while", "xor", "yield", "yield", "from",
      "readonly", "enum", "never", "void", "self", "parent",
    ],
    builtins: [
      "true", "false", "null", "TRUE", "FALSE", "NULL",
      "string", "int", "integer", "float", "double",
      "bool", "boolean", "array", "object", "callable",
      "iterable", "mixed", "never", "void", "self",
      "parent", "static",
      "strlen", "substr", "strpos", "strrpos", "strtolower",
      "strtoupper", "ucfirst", "lcfirst", "trim", "ltrim",
      "rtrim", "str_replace", "str_ireplace", "explode",
      "implode", "join", "str_split", "chunk_split",
      "str_pad", "str_repeat", "str_contains", "str_starts_with",
      "str_ends_with", "htmlspecialchars", "htmlentities",
      "nl2br", "number_format", "sprintf", "printf",
      "count", "array_push", "array_pop", "array_shift",
      "array_unshift", "array_map", "array_filter",
      "array_reduce", "array_merge", "array_keys",
      "array_values", "array_unique", "array_sort",
      "sort", "usort", "in_array", "array_key_exists",
      "isset", "empty", "unset", "var_dump", "print_r",
      "is_array", "is_string", "is_int", "is_numeric",
      "is_null", "is_bool", "is_object", "gettype",
      "settype", "intval", "floatval", "strval",
      "abs", "ceil", "floor", "round", "max", "min",
      "rand", "mt_rand", "date", "time", "strtotime",
      "mktime", "checkdate", "file_exists", "file_get_contents",
      "file_put_contents", "json_encode", "json_decode",
      "htmlspecialchars_decode", "preg_match", "preg_replace",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Scripting: Lua ───────────────────────────────────────────
  lua: {
    name: "Lua",
    keywords: [
      "and", "break", "do", "else", "elseif", "end",
      "false", "for", "function", "goto", "if", "in",
      "local", "nil", "not", "or", "repeat", "return",
      "then", "true", "until", "while",
    ],
    builtins: [
      "print", "type", "tostring", "tonumber", "pairs",
      "ipairs", "error", "pcall", "xpcall", "assert",
      "collectgarbage", "select", "unpack", "rawget",
      "rawset", "rawequal", "rawlen", "setmetatable",
      "getmetatable", "load", "loadstring", "dofile",
      "require", "module", "string", "byte", "char",
      "find", "format", "gmatch", "gsub", "len", "lower",
      "match", "rep", "reverse", "sub", "upper", "concat",
      "table", "insert", "remove", "sort", "concat",
      "maxn", "math", "abs", "ceil", "floor", "max",
      "min", "fmod", "sqrt", "pow", "exp", "log",
      "log10", "random", "randomseed", "huge", "pi",
      "sin", "cos", "tan", "asin", "acos", "atan",
      "deg", "rad", "io", "read", "write", "close",
      "flush", "input", "output", "lines", "open",
      "popen", "tmpfile", "type", "os", "clock",
      "date", "difftime", "execute", "exit", "getenv",
      "remove", "rename", "setlocale", "time",
      "tmpname", "coroutine", "create", "resume",
      "yield", "status", "wrap", "running",
    ],
    commentSingle: "--",
    commentMulti: ["--[[", "]]"],
    stringChars: ['"', "'"],
  },

  // ─── Scripting: Dart ──────────────────────────────────────────
  dart: {
    name: "Dart",
    keywords: [
      "assert", "break", "case", "catch", "class", "const",
      "continue", "default", "do", "else", "enum", "extends",
      "false", "final", "finally", "for", "if", "in", "is",
      "new", "null", "rethrow", "return", "super", "switch",
      "this", "throw", "true", "try", "var", "void", "while",
      "with", "async", "await", "yield", "library", "import",
      "export", "part", "show", "hide", "late", "required",
      "sealed", "interface", "mixin", "extension", "on",
      "static", "factory", "operator", "get", "set",
      "external", "covariant", "dynamic", "base",
    ],
    builtins: [
      "int", "double", "num", "bool", "String", "List",
      "Map", "Set", "Queue", "Iterator", "Iterable",
      "Symbol", "Null", "Object", "Function", "Type",
      "Future", "Stream", "Completer", "RegExp",
      "DateTime", "Duration", "Uri", "BigInt",
      "print", "toString", "runtimeType", "hashCode",
      "noSuchMethod", "add", "remove", "clear", "length",
      "isEmpty", "isNotEmpty", "first", "last", "indexOf",
      "lastIndexOf", "contains", "sublist", "forEach",
      "map", "where", "expand", "reduce", "fold",
      "every", "any", "firstWhere", "lastWhere",
      "singleWhere", "toList", "toSet", "sort",
      "shuffle", "reversed", "skip", "take", "cast",
      "getRange", "fillRange", "join", "split",
      "substring", "replaceAll", "replaceFirst",
      "toLowerCase", "toUpperCase", "trim", "trimLeft",
      "trimRight", "startsWith", "endsWith", "padLeft",
      "padRight", "containsKey", "containsValue",
      "putIfAbsent", "update", "updateAll", "removeWhere",
      "entries", "keys", "values", "forEach",
      "map", "length", "isEmpty", "addAll",
      "Uint8List", "int8List", "File", "Directory",
      "Platform", "stdin", "stdout", "stderr",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Scripting: Groovy ────────────────────────────────────────
  groovy: {
    name: "Groovy",
    keywords: [
      "abstract", "as", "assert", "break", "case", "catch",
      "class", "const", "continue", "def", "default", "do",
      "else", "enum", "extends", "false", "final", "finally",
      "for", "goto", "if", "implements", "import", "in",
      "instanceof", "interface", "native", "new", "null",
      "package", "private", "protected", "public", "return",
      "static", "strictfp", "super", "switch", "synchronized",
      "this", "throw", "throws", "trait", "transient",
      "true", "try", "void", "volatile", "while",
      "it", "yield",
    ],
    builtins: [
      "println", "print", "sprintf", "printf", "readLine",
      "String", "Integer", "Long", "Double", "Float",
      "Boolean", "Byte", "Short", "Character", "BigInteger",
      "BigDecimal", "Object", "Class", "Thread", "Exception",
      "RuntimeException", "ArrayList", "LinkedList",
      "HashMap", "LinkedHashMap", "HashSet", "TreeMap",
      "TreeSet", "Range", "Regex", "Pattern", "Matcher",
      "File", "Writer", "Reader", "InputStream", "OutputStream",
      "BufferedReader", "BufferedWriter", "FileReader",
      "FileWriter", "System", "Math", "Arrays", "Collections",
      "Date", "Calendar", "SimpleDateFormat", "UUID",
      "each", "collect", "find", "findAll", "grep",
      "inject", "eachWithIndex", "sort", "reverse",
      "unique", "flatten", "join", "split", "tokenize",
      "substring", "toUpperCase", "toLowerCase", "trim",
      "size", "length", "isEmpty", "contains",
      "startsWith", "endsWith", "replaceAll",
      "replaceFirst", "capitalize", "reverse",
      "leftShift", "rightShift", "with", "execute",
      "withReader", "withWriter", "withInputStream",
      "withOutputStream", "eachLine", "eachFile",
      "eachDir", "traverse", "eachFileRecurse",
      "eachDirRecurse", "getText", "write", "append",
      "withStream", "respondsTo", "metaClass",
      "getProperty", "setProperty", "invokeMethod",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'", '"""', "'''"],
  },

  // ─── Markup: LaTeX ────────────────────────────────────────────
  latex: {
    name: "LaTeX",
    keywords: [
      "documentclass", "usepackage", "begin", "end",
      "section", "subsection", "subsubsection", "paragraph",
      "subparagraph", "chapter", "part", "appendix",
      "title", "author", "date", "maketitle", "tableofcontents",
      "listoffigures", "listoftables", "bibliography",
      "bibliographystyle", "cite", "label", "ref", "eqref",
      "pageref", "autoref", "cref", "Cref", "caption",
      "includegraphics", "include", "input", "import",
      "subfile", "newcommand", "renewcommand",
      "newenvironment", "newtheorem", "theoremstyle",
      "theorem", "lemma", "corollary", "proof", "definition",
      "example", "remark", "item", "textbf", "textit",
      "texttt", "emph", "underline", "textsc", "textrm",
      "textsf", "textsl", "footnote", "marginnote",
      "footnotemark", "footnotetext", "href", "url",
      "hyperlink", "hypertarget",
    ],
    builtins: [
      "figure", "table", "tabular", "array", "matrix",
      "pmatrix", "bmatrix", "vmatrix", "cases", "aligned",
      "gather", "equation", "equation*", "align", "align*",
      "multline", "split", "subequations", "frac", "dfrac",
      "tfrac", "sqrt", "sum", "prod", "int", "iint",
      "iiint", "oint", "lim", "sup", "inf", "min", "max",
      "log", "ln", "exp", "sin", "cos", "tan", "cot",
      "sec", "csc", "arcsin", "arccos", "arctan",
      "sinh", "cosh", "tanh", "partial", "nabla",
      "infty", "hline", "toprule", "midrule", "bottomrule",
      "cmidrule", "cline", "multicolumn", "multirow",
      "rowcolor", "cellcolor", "columncolor", "top",
      "bottom", "centering", "raggedright", "raggedleft",
      "justify", "noindent", "indent", "par", "newline",
      "linebreak", "pagebreak", "newpage", "clearpage",
      "vspace", "hspace", "vfill", "hfill", "mbox",
      "fbox", "framebox", "parbox", "minipage",
      "columnwidth", "textwidth", "linewidth", "pagewidth",
      "纸张", "geometry", "setlength", "addtolength",
      "left", "right", "center", "raggedleft", "raggedright",
      "itemize", "enumerate", "description", "item",
      "alpha", "beta", "gamma", "delta", "epsilon",
      "zeta", "eta", "theta", "lambda", "mu", "nu",
      "xi", "pi", "rho", "sigma", "tau", "phi", "chi",
      "psi", "omega", "left", "right", "big", "Big",
      "bigg", "Bigg", "cdot", "cdots", "ldots", "vdots",
      "ddots", "quad", "qquad",
    ],
    commentSingle: "%",
    commentMulti: ["", ""],
    stringChars: ['{'],
  },

  // ─── Markup: Markdown ─────────────────────────────────────────
  markdown: {
    name: "Markdown",
    keywords: [
      "heading", "h1", "h2", "h3", "h4", "h5", "h6",
      "bold", "italic", "strikethrough", "blockquote",
      "code", "codeblock", "link", "image", "list",
      "ordered", "unordered", "tasklist", "table",
      "horizontal", "rule", "thematic", "break",
      "checkbox",
    ],
    builtins: [
      "#", "##", "###", "####", "#####", "######",
      "**bold**", "__bold__", "*italic*", "_italic_",
      "***bold+italic***", "~~strikethrough~~", ">",
      "`code`", "```", "[text]", "(url)", "![alt]",
      "-", "*", "+", "1.", "2.", "3.", "[x]", "[ ]",
      "|", "---", "|---|", "|:---|", "|---:|", "|:---:|",
      "---", "***",
    ],
    commentSingle: "",
    commentMulti: ["<!--", "-->"],
    stringChars: [],
  },

  // ─── Markup: Dockerfile ───────────────────────────────────────
  dockerfile: {
    name: "Dockerfile",
    keywords: [
      "FROM", "RUN", "CMD", "LABEL", "MAINTAINER", "EXPOSE",
      "ENV", "ADD", "COPY", "ENTRYPOINT", "VOLUME",
      "USER", "WORKDIR", "ARG", "ONBUILD", "STOPSIGNAL",
      "HEALTHCHECK", "SHELL", "AS",
    ],
    builtins: [
      "apt-get", "update", "install", "rm", "curl", "wget",
      "tar", "unzip", "chmod", "mkdir", "cd", "mv", "cp",
      "pip", "npm", "yarn", "pnpm", "bun", "go", "cargo",
      "java", "python", "node", "alpine", "ubuntu", "debian",
      "centos", "fedora", "python", "node", "slim",
      "buster", "bullseye", "bookworm", "focal", "jammy",
      "latest", "stable", "set", "exec", "form",
      "no-install-recommends", "autoremove", "clean",
    ],
    commentSingle: "#",
    commentMulti: ["", ""],
    stringChars: ['"', "'"],
  },

  // ─── Markup: Makefile ─────────────────────────────────────────
  makefile: {
    name: "Makefile",
    keywords: [
      "define", "endef", "ifdef", "ifndef", "ifeq", "ifneq",
      "else", "endif", "include", "override", "export",
      "unexport", "private", "vpath", "undefine",
    ],
    builtins: [
      "CC", "CXX", "LD", "AR", "CFLAGS", "CXXFLAGS",
      "LDFLAGS", "CPPFLAGS", "LDLIBS", "TARGET", "TARGETS",
      "SRC", "SRCS", "OBJS", "OBJ", "HEADERS", "INCLUDES",
      "all", "clean", "install", "uninstall", "test",
      "check", "dist", "distclean", "help", "info",
      "build", "release", "debug", ".PHONY", ".SUFFIXES",
      ".DEFAULT", ".PRECIOUS", ".INTERMEDIATE",
      ".SECONDARY", ".DELETE_ON_ERROR", ".SILENT",
      ".IGNORE", ".LOW_RESOLUTION_TIME",
      "@", "-", "+", "$@", "$<", "$^", "$?", "$*",
      "$(@D)", "$(@F)", "$(CC)", "$(CXX)", "$(MAKE)",
      "make", "mkdir", "rm", "cp", "mv", "touch",
      "echo", "cat", "install", "strip", "ar", "ranlib",
      "pkg-config", "cmake", "pip", "npm", "go",
      "shell", "wildcard", "patsubst", "subst", "strip",
      "findstring", "filter", "filter-out", "sort",
      "word", "words", "wordlist", "firstword",
      "lastword", "dir", "notdir", "suffix", "basename",
      "addsuffix", "addprefix", "join", "realpath",
      "abspath", "if", "or", "and", "call", "value",
      "origin", "flavor", "foreach", "eval", "error",
      "warning", "info", "shell",
    ],
    commentSingle: "#",
    commentMulti: ["", ""],
    stringChars: ['"', "'"],
  },

  // ─── Markup: INI ──────────────────────────────────────────────
  ini: {
    name: "INI",
    keywords: [
      "global", "default", "general", "main", "common",
      "database", "server", "client", "logging", "cache",
      "session", "security", "network", "email", "storage",
    ],
    builtins: [
      "host", "port", "user", "username", "password",
      "database", "name", "path", "file", "dir", "directory",
      "url", "address", "ip", "timeout", "interval",
      "max_connections", "pool_size", "buffer_size",
      "debug", "verbose", "level", "format", "output",
      "input", "enable", "disable", "true", "false",
      "yes", "no", "on", "off", "encoding", "charset",
      "language", "locale", "timezone", "key", "secret",
      "token", "certificate", "ssl", "tls", "http",
      "https", "cors", "allowed_origins",
    ],
    commentSingle: ";",
    commentMulti: ["", ""],
    stringChars: [],
  },

  // ─── Other: Assembly (x86) ───────────────────────────────────
  assembly: {
    name: "Assembly",
    keywords: [
      "mov", "push", "pop", "add", "sub", "mul", "div",
      "inc", "dec", "neg", "not", "and", "or", "xor",
      "shl", "shr", "sar", "rol", "ror", "cmp", "test",
      "jmp", "je", "jne", "jz", "jnz", "jg", "jl", "jge",
      "jle", "ja", "jb", "jae", "jbe", "jcxz", "loop",
      "call", "ret", "enter", "leave", "nop", "hlt",
      "int", "iret", "cli", "sti", "cld", "std",
      "lea", "xchg", "cmpxchg", "bswap",
      "movzx", "movsx", "cdq", "cwd", "cbw", "cwde",
      "pushf", "popf", "pushad", "popad", "pusha", "popa",
      "rep", "repe", "repne", "repz", "repnz", "movsb",
      "movsw", "movsd", "stosb", "stosw", "stosd",
      "lodsb", "lodsw", "lodsd", "scasb", "scasw", "scasd",
      "insb", "insw", "insd", "outsb", "outsw", "outsd",
    ],
    builtins: [
      "eax", "ebx", "ecx", "edx", "esi", "edi", "ebp",
      "esp", "ax", "bx", "cx", "dx", "si", "di", "bp",
      "sp", "al", "ah", "bl", "bh", "cl", "ch", "dl",
      "dh", "cs", "ds", "es", "fs", "gs", "ss", "eip",
      "eflags", "cr0", "cr2", "cr3", "cr4", "dr0", "dr1",
      "dr2", "dr3", "dr6", "dr7", "mm0", "mm1", "mm2",
      "mm3", "mm4", "mm5", "mm6", "mm7", "xmm0", "xmm1",
      "xmm2", "xmm3", "xmm4", "xmm5", "xmm6", "xmm7",
      "ymm0", "ymm1", "ymm2", "ymm3", "ymm4", "ymm5",
      "ymm6", "ymm7", "zmm0", "zmm1", "r8", "r9", "r10",
      "r11", "r12", "r13", "r14", "r15", "r8d", "r9d",
      "r10d", "r11d", "r12d", "r13d", "r14d", "r15d",
      "r8w", "r9w", "r8b", "r9b", "byte", "word", "dword",
      "qword", "ptr", "offset", "section", "global",
      "extern", "db", "dw", "dd", "dq", "dt", "equ",
      "times", "org", "bits", "section", "segment",
    ],
    commentSingle: ";",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
    caseInsensitive: true,
  },

  // ─── Other: Solidity ──────────────────────────────────────────
  solidity: {
    name: "Solidity",
    keywords: [
      "pragma", "solidity", "import", "from", "as",
      "contract", "library", "interface", "abstract",
      "is", "function", "modifier", "event", "error",
      "struct", "enum", "mapping", "constructor",
      "receive", "fallback", "using", "for", "return",
      "returns", "emit", "revert", "require", "assert",
      "if", "else", "while", "do", "break", "continue",
      "throw", "new", "delete", "this", "super", "selfdestruct",
      "suicide", "type", "var", "let", "constant",
      "immutable", "override", "virtual", "public",
      "private", "internal", "external", "storage",
      "memory", "calldata", "payable", "pure", "view",
      "indexed", "anonymous", "unchecked", "assembly",
    ],
    builtins: [
      "address", "uint", "uint8", "uint16", "uint32",
      "uint64", "uint128", "uint256", "int", "int8",
      "int16", "int32", "int64", "int128", "int256",
      "bool", "string", "bytes", "bytes1", "bytes2",
      "bytes3", "bytes4", "bytes5", "bytes6", "bytes7",
      "bytes8", "bytes9", "bytes10", "bytes11",
      "bytes12", "bytes13", "bytes14", "bytes15",
      "bytes16", "bytes17", "bytes18", "bytes19",
      "bytes20", "bytes21", "bytes22", "bytes23",
      "bytes24", "bytes25", "bytes26", "bytes27",
      "bytes28", "bytes29", "bytes30", "bytes31",
      "bytes32", "msg", "sender", "value", "data",
      "sig", "block", "timestamp", "number",
      "difficulty", "gaslimit", "chainid", "coinbase",
      "basefee", "prevrandao", "tx", "origin", "gasprice",
      "blockhash", "abi", "encode", "decode",
      "encodePacked", "encodeWithSelector",
      "decodeWithSelector", "encodeCall",
      "keccak256", "sha256", "ripemd160", "ecrecover",
      "ecrecover", "mulmod", "addmod", "now",
      "true", "false", "payable", "type",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Other: CoffeeScript ──────────────────────────────────────
  coffeescript: {
    name: "CoffeeScript",
    keywords: [
      "if", "else", "else if", "for", "while", "until",
      "loop", "switch", "when", "then", "return", "try",
      "catch", "finally", "throw", "break", "continue",
      "class", "extends", "super", "new", "delete",
      "typeof", "instanceof", "import", "export",
      "from", "default", "yield", "await", "async",
      "of", "by", "in", "is", "isnt", "not", "and",
      "or", "unless", "do",
    ],
    builtins: [
      "true", "false", "yes", "no", "on", "off", "null",
      "undefined", "NaN", "Infinity", "console", "log",
      "error", "warn", "info", "dir", "time", "timeEnd",
      "Math", "Array", "Object", "String", "Number",
      "Boolean", "RegExp", "Date", "JSON", "Promise",
      "setTimeout", "setInterval", "clearTimeout",
      "clearInterval", "require", "module", "exports",
      "process", "__dirname", "__filename", "arguments",
      "parseInt", "parseFloat", "isNaN", "isFinite",
      "encodeURI", "decodeURI", "encodeURIComponent",
      "decodeURIComponent", "Error", "TypeError",
      "RangeError", "SyntaxError", "Map", "Set", "WeakMap",
      "Symbol", "Proxy", "Reflect", "globalThis",
    ],
    commentSingle: "#",
    commentMulti: ["###", "###"],
    stringChars: ['"', "'", '"""', "'''"],
  },

  // ─── Other: SCSS ──────────────────────────────────────────────
  scss: {
    name: "SCSS",
    keywords: [
      "color", "background", "background-color",
      "background-image", "background-size",
      "background-position", "background-repeat", "border",
      "border-radius", "border-color", "border-width",
      "border-style", "margin", "margin-top", "margin-right",
      "margin-bottom", "margin-left", "padding", "padding-top",
      "padding-right", "padding-bottom", "padding-left",
      "width", "height", "min-width", "max-width",
      "min-height", "max-height", "display", "position",
      "top", "right", "bottom", "left", "float", "clear",
      "overflow", "font-family", "font-size", "font-weight",
      "font-style", "line-height", "text-align",
      "text-decoration", "text-transform", "white-space",
      "flex", "flex-direction", "flex-wrap", "flex-flow",
      "justify-content", "align-items", "align-self",
      "grid", "grid-template-columns", "grid-template-rows",
      "gap", "box-shadow", "opacity", "z-index", "cursor",
      "transition", "transform", "animation", "content",
      "outline", "box-sizing", "filter", "object-fit",
    ],
    builtins: [
      "@import", "@use", "@forward", "@mixin", "@include",
      "@function", "@return", "@extend", "@at-root",
      "@debug", "@warn", "@error", "@if", "@else",
      "@else if", "@each", "@for", "@while", "@media",
      "@keyframes", "@font-face", "@supports", "@layer",
      "@charset", "@namespace", "@page", "@counter-style",
      "@property", "$", "!", "default", "global",
      "null", "true", "false", "not", "and", "or",
      "nth", "length", "append", "zip", "index",
      "join", "list-separator", "type-of", "unit",
      "unitless", "comparable", "percentage", "round",
      "ceil", "floor", "abs", "min", "max", "random",
      "if", "lighten", "darken", "saturate", "desaturate",
      "adjust-hue", "opacify", "fade-in", "transparentize",
      "fade-out", "mix", "complement", "invert", "grayscale",
      "hsl", "hsla", "rgb", "rgba", "red", "green",
      "blue", "hue", "saturation", "lightness", "alpha",
      "map-get", "map-merge", "map-remove", "map-keys",
      "map-values", "map-has-key", "keywords",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Other: Sass ──────────────────────────────────────────────
  sass: {
    name: "Sass",
    keywords: [
      "color", "background", "background-color",
      "background-image", "background-size",
      "background-position", "background-repeat", "border",
      "border-radius", "border-color", "border-width",
      "border-style", "margin", "padding", "width", "height",
      "min-width", "max-width", "min-height", "max-height",
      "display", "position", "top", "right", "bottom", "left",
      "float", "clear", "overflow", "font-family", "font-size",
      "font-weight", "font-style", "line-height",
      "text-align", "text-decoration", "text-transform",
      "white-space", "flex", "flex-direction", "flex-wrap",
      "justify-content", "align-items", "grid",
      "grid-template-columns", "grid-template-rows", "gap",
      "box-shadow", "opacity", "z-index", "cursor",
      "transition", "transform", "animation", "content",
      "outline", "box-sizing", "filter",
    ],
    builtins: [
      "@import", "@use", "@forward", "@mixin", "@include",
      "@function", "@return", "@extend", "@at-root",
      "@debug", "@warn", "@error", "@if", "@else",
      "@else if", "@each", "@for", "@while", "@media",
      "@keyframes", "@font-face", "@supports", "@layer",
      "!default", "!global", "!important", "null", "true",
      "false", "not", "and", "or", "nth", "length",
      "append", "zip", "index", "join", "type-of", "unit",
      "unitless", "comparable", "percentage", "round",
      "ceil", "floor", "abs", "min", "max", "random",
      "lighten", "darken", "saturate", "desaturate",
      "adjust-hue", "opacify", "transparentize", "mix",
      "complement", "grayscale", "hsl", "hsla", "rgb",
      "rgba", "red", "green", "blue", "hue", "saturation",
      "lightness", "alpha", "map-get", "map-merge",
      "map-remove", "map-keys", "map-values",
      "map-has-key",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Other: Less ──────────────────────────────────────────────
  less: {
    name: "Less",
    keywords: [
      "color", "background", "background-color",
      "background-image", "background-size",
      "background-position", "background-repeat", "border",
      "border-radius", "border-color", "border-width",
      "border-style", "margin", "padding", "width", "height",
      "min-width", "max-width", "min-height", "max-height",
      "display", "position", "top", "right", "bottom", "left",
      "float", "clear", "overflow", "font-family", "font-size",
      "font-weight", "font-style", "line-height",
      "text-align", "text-decoration", "text-transform",
      "white-space", "flex", "flex-direction", "flex-wrap",
      "justify-content", "align-items", "grid",
      "grid-template-columns", "grid-template-rows", "gap",
      "box-shadow", "opacity", "z-index", "cursor",
      "transition", "transform", "animation", "content",
      "outline", "box-sizing", "filter",
    ],
    builtins: [
      "@import", "@charset", "@namespace", "@keyframes",
      "@media", "@supports", "@font-face", "@plugin",
      "@property", "when", "and", "not", "only",
      "escape", "e", "replace", "%", "format",
      "length", "extract", "range", "each", "index",
      "isnumber", "isstring", "iscolor", "iskeyword",
      "isurl", "ispixel", "isem", "ispercentage",
      "isunit", "isruleset", "iscolor", "multiply",
      "add", "subtract", "divide", "ceil", "floor",
      "percentage", "round", "sqrt", "abs", "sin",
      "asin", "cos", "acos", "tan", "atan", "pi",
      "pow", "mod", "min", "max", "convert", "unit",
      "data-uri", "image-size", "image-width",
      "image-height",
      "@arguments", "@rest", "@import", "@variable",
      "all", "color-blend", "color", "luma", "lighten",
      "darken", "saturate", "desaturate", "fadein",
      "fadeout", "fade", "spin", "mix", "contrast",
      "greyscale", "hsv", "hsva", "hsl", "hsla",
      "hue", "saturation", "lightness", "alpha", "red",
      "green", "blue", "luma", "spin", "hardlight",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Additional: Objective-C ─────────────────────────────────
  "objective-c": {
    name: "Objective-C",
    keywords: [
      "auto", "break", "case", "char", "const", "continue",
      "default", "do", "double", "else", "enum", "extern",
      "float", "for", "goto", "if", "inline", "int", "long",
      "register", "restrict", "return", "short", "signed",
      "sizeof", "static", "struct", "switch", "typedef",
      "union", "unsigned", "void", "volatile", "while",
      "@interface", "@implementation", "@protocol",
      "@class", "@property", "@synthesize", "@dynamic",
      "@end", "@try", "@catch", "@finally", "@throw",
      "@optional", "@required", "@package", "@public",
      "@protected", "@private", "@selector", "@encode",
      "@defs", "@property", "nonatomic", "atomic",
      "strong", "weak", "copy", "retain", "assign",
      "readonly", "readwrite", "getter", "setter",
      "nullable", "nonnull", "null_unspecified",
      "null_resettable", "class", "instancetype", "id",
      "BOOL", "YES", "NO", "nil", "Nil", "SEL", "IMP",
      "Block", "dispatch_block_t",
    ],
    builtins: [
      "NSObject", "NSString", "NSArray", "NSMutableArray",
      "NSDictionary", "NSMutableDictionary", "NSSet",
      "NSMutableSet", "NSNumber", "NSData", "NSMutableData",
      "NSDate", "NSCalendar", "NSTimeZone", "NSError",
      "NSURL", "NSURLRequest", "NSURLSession", "NSBundle",
      "NSFileManager", "NSRunLoop", "NSNotification",
      "NSNotificationCenter", "NSUserDefaults", "NSLock",
      "NSRecursiveLock", "NSOperation", "NSBlockOperation",
      "NSInvocationOperation", "NSOperationQueue",
      "GCD", "dispatch_async", "dispatch_sync",
      "dispatch_after", "dispatch_once", "dispatch_group",
      "dispatch_semaphore", "dispatch_queue_create",
      "dispatch_get_main_queue", "dispatch_get_global_queue",
      "NSLog", "NSAssert", "NSRange", "NSPoint",
      "NSSize", "NSRect", "NSInteger", "NSUInteger",
      "CGFloat", "CGRectMake", "CGPointMake",
      "CGSizeMake", "UIScreen", "UIView", "UIViewController",
      "UILabel", "UIButton", "UIImageView", "UITableView",
      "UITableViewCell", "UIScrollView", "UITextField",
      "UITextView", "UIColor", "UIFont", "UIImage",
      "self", "super", "_cmd", "alloc", "init", "new",
      "release", "autorelease", "retain", "retainCount",
      "dealloc", "copy", "mutableCopy", "class",
      "isKindOfClass", "isMemberOfClass",
      "respondsToSelector", "performSelector",
      "isEqual", "hash", "description", "debugDescription",
      "setValue", "forKey", "valueForKey",
      "addObject", "removeObject", "objectAtIndex",
      "count", "enumerateObjectsUsingBlock",
      "makeObjectsPerformSelector", "sortUsingComparator",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Additional: Vue ──────────────────────────────────────────
  vue: {
    name: "Vue",
    keywords: [
      "setup", "script", "template", "style", "props",
      "emit", "defineProps", "defineEmits", "defineExpose",
      "defineModel", "defineSlots", "defineComponent",
      "ref", "reactive", "computed", "watch", "watchEffect",
      "onMounted", "onUnmounted", "onUpdated", "onBeforeMount",
      "onBeforeUnmount", "onBeforeUpdate", "onActivated",
      "onDeactivated", "onErrorCaptured",
      "provide", "inject", "readonly", "toRef", "toRefs",
      "isRef", "unref", "shallowRef", "shallowReactive",
      "triggerRef", "nextTick", "defineAsyncComponent",
      "Suspense", "Teleport", "Transition", "TransitionGroup",
      "KeepAlive", "slot", "v-if", "v-else", "v-else-if",
      "v-for", "v-show", "v-model", "v-bind", "v-on",
      "v-slot", "v-html", "v-text", "v-once", "v-memo",
    ],
    builtins: [
      "app", "createApp", "component", "directive", "mixin",
      "use", "mount", "unmount", "config", "version",
      "router", "route", "useRouter", "useRoute",
      "pinia", "defineStore", "storeToRefs",
      "vue", "reactive", "effect", "effectScope",
      "getCurrentInstance", "getCurrentScope",
      "h", "resolveComponent", "resolveDirective",
      "withDirectives", "mergeProps", "setBlockTracking",
      "createVNode", "cloneVNode", "isVNode",
      "transformVNodeArgs", "createElement",
      "render", "renderList", "renderSlot",
      "createTextVNode", "createStaticVNode",
      "resolveDynamicComponent", "openBlock",
      "createBlock", "createCommentVNode",
      "Transition", "BaseTransition",
      "KeepAlive", "Teleport", "Suspense",
      "true", "false", "null", "undefined",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'", "`"],
  },

  // ─── Additional: Svelte ───────────────────────────────────────
  svelte: {
    name: "Svelte",
    keywords: [
      "script", "style", "template", "export", "let",
      "const", "var", "function", "class", "if", "else",
      "each", "await", "then", "catch", "key", "slot",
      "svelte", "self", "component", "transition",
      "animate", "action", "use", "on", "bind", "dispatch",
      "createEventDispatcher", "setContext", "getContext",
      "tick", "afterUpdate", "beforeUpdate",
      "onMount", "onDestroy", "on:introstart",
      "on:introend", "on:outrostart", "on:outroend",
      "immutable", "refresh", "props", "$", "reactive",
      "derived", "store", "writable", "readable",
    ],
    builtins: [
      "fade", "fly", "slide", "scale", "draw", "crossfade",
      "flip", "spring", "tweened", "linear", "backInOut",
      "backIn", "backOut", "bounceInOut", "bounceIn",
      "bounceOut", "circInOut", "circIn", "circOut",
      "cubicInOut", "cubicIn", "cubicOut", "elasticInOut",
      "elasticIn", "elasticOut", "expoInOut", "expoIn",
      "expoOut", "quadInOut", "quadIn", "quadOut",
      "quartInOut", "quartIn", "quartOut", "quintInOut",
      "quintIn", "quintOut", "sineInOut", "sineIn",
      "sineOut", "spring", "Action", "Transition",
      "Animation", "SvelteComponent", "SvelteComponentTyped",
      "create_svelte_component", "svelteHTML",
      "svelteSSR", "svelteHead", "svelteStore",
      "true", "false", "null", "undefined",
      "console", "document", "window", "Math", "JSON",
      "Promise", "Array", "Object", "String", "Number",
      "Map", "Set", "Date", "RegExp", "Error",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"', "'"],
  },

  // ─── Additional: Zig ──────────────────────────────────────────
  zig: {
    name: "Zig",
    keywords: [
      "const", "var", "pub", "export", "extern",
      "fn", "return", "if", "else", "switch", "for",
      "while", "break", "continue", "defer", "errdefer",
      "struct", "enum", "union", "opaque", "error",
      "try", "catch", "orelse", "and", "or", "not",
      "test", "comptime", "defer", "unreachable",
      "suspend", "resume", "async", "await", "nosuspend",
      "alloc", "free", "align", "linksection",
      "addrspace", "callconv", "threadlocal", "volatile",
      "allowzero", "noalias", "noinline", "packed",
    ],
    builtins: [
      "bool", "f16", "f32", "f64", "f80", "f128",
      "i8", "i16", "i32", "i64", "i128", "isize",
      "u8", "u16", "u32", "u64", "u128", "usize",
      "c_short", "c_ushort", "c_int", "c_uint",
      "c_long", "c_ulong", "c_longlong", "c_ulonglong",
      "c_float", "c_double", "c_longdouble",
      "void", "noreturn", "type", "anytype",
      "anyerror", "comptime_int", "comptime_float",
      "true", "false", "null", "undefined",
      "std", "mem", "fmt", "log", "debug", "testing",
      "Allocator", "ArrayList", "HashMap", "StringHashMap",
      "Process", "Child", "BufSet", "BufMap",
      "File", "Dir", "process", "math", "ascii",
      "crypto", "hash", "meta", "builtin",
      "println", "eprintln", "print", "debugPrint",
      "warn", "info", "err", "panic", "unreachable",
      "expect", "expectEqual", "expectError",
      "expectApproxEqAbs", "alloc", "create", "init",
      "deinit", "items", "len", "append", "pop",
      "iterator", "sort", "copy", "max", "min",
      "abs", "ceil", "floor", "log", "log2", "log10",
      "sqrt", "sin", "cos", "round",
    ],
    commentSingle: "//",
    commentMulti: ["/*", "*/"],
    stringChars: ['"'],
  },

  // ─── Additional: Nim ──────────────────────────────────────────
  nim: {
    name: "Nim",
    keywords: [
      "addr", "and", "as", "asm", "bind", "block", "break",
      "case", "cast", "concept", "const", "continue",
      "converter", "defer", "discard", "distinct", "div",
      "do", "elif", "else", "end", "enum", "except",
      "export", "finally", "for", "from", "func", "if",
      "import", "include", "in", "interface", "is", "isnot",
      "iterator", "let", "macro", "method", "mixin", "mod",
      "nil", "not", "notin", "object", "of", "or", "out",
      "proc", "ptr", "raise", "ref", "return", "shl", "shr",
      "static", "template", "try", "tuple", "type",
      "using", "var", "when", "while", "xor", "yield",
    ],
    builtins: [
      "int", "int8", "int16", "int32", "int64",
      "uint", "uint8", "uint16", "uint32", "uint64",
      "float", "float32", "float64", "bool", "char",
      "string", "cstring", "pointer", "seq", "array",
      "openArray", "varargs", "UncheckedArray",
      "set", "HashSet", "Table", "OrderedTable",
      "TableRef", "OrderedTableRef", "CritBitTree",
      "tuple", "object", "ref", "ptr", "proc",
      "iterator", "distinct", "range", "Slice",
      "void", "auto", "any", "some", "typedesc",
      "untyped", "typed", "static", "echo", "write",
      "writeLine", "readLine", "readFile", "writeFile",
      "format", "fmt", "parse", "parseInt", "parseFloat",
      "len", "high", "low", "add", "delete", "contains",
      "incl", "excl", "card", "items", "pairs", "mitems",
      "mpairs", "new", "newSeq", "newSeqOfCap",
      "openArray", "alloc", "alloc0", "dealloc",
      "realloc", "copyMem", "moveMem", "equalMem",
      "zeroMem", "abs", "clamp", "min", "max",
      "sorted", "sort", "reverse", "map", "filter",
      "foldl", "foldr", "count", "any", "all",
      "find", "contains", "join", "split", "strip",
      "startsWith", "endsWith", "replace", "toUpper",
      "toLower", "repeat", "substr",
    ],
    commentSingle: "#",
    commentMulti: ["#[", "]#"],
    stringChars: ['"', "'"],
  },

  // ─── Additional: Vim Script ───────────────────────────────────
  vimscript: {
    name: "Vim Script",
    keywords: [
      "function", "endfunction", "if", "endif", "else",
      "elseif", "while", "endwhile", "for", "endfor",
      "try", "endtry", "catch", "finally", "throw",
      "let", "unlet", "const", "call", "return", "echo",
      "echom", "echoerr", "execute", "normal", "source",
      "set", "setlocal", "setglobal", "let", "map",
      "nmap", "imap", "vmap", "smap", "xmap", "omap",
      "cmap", "lmap", "tmap", "nnoremap", "inoremap",
      "vnoremap", "snoremap", "xnoremap", "onoremap",
      "cnoremap", "lnoremap", "tnoremap", "noremap",
      "unmap", "nunmap", "iunmap", "vunmap",
      "autocmd", "augroup", "command", "function",
      "script", "finish", "runtime", "packadd",
      "syntax", "filetype", "highlight", "hi",
      "syn", "match", "region", "keyword", "contained",
      "nextgroup", "contains", "skipwhite", "transparent",
    ],
    builtins: [
      "g:", "l:", "s:", "a:", "v:", "b:", "w:", "t:",
      "$", "@", "&", "exists", "type", "len", "empty",
      "has", "has_key", "keys", "values", "items",
      "remove", "extend", "copy", "deepcopy", "sort",
      "reverse", "map", "filter", "split", "join",
      "substitute", "submatch", "tr", "tolower",
      "toupper", "str2nr", "nr2str", "printf",
      "input", "inputsave", "inputrestore", "getchar",
      "getcharstr", "getline", "readfile", "writefile",
      "system", "systemlist", "execute", "expand",
      "expandcmd", "fnamemodify", "resolve", "simplify",
      "executable", "bufnr", "bufname", "bufwinnr",
      "winbufnr", "winwidth", "winheight", "tabpagebuflist",
      "line", "col", "virtcol", "wordcount",
      "getpos", "setpos", "getcurpos", "getcwd",
      "haslocaldir", "lcd", "cd", "pwd",
      "search", "searchpos", "searchpair",
      "match", "matchend", "matchstr", "matchlist",
      "substitute", "stridx", "strridx", "strlen",
      "strpart", "strdisplaywidth", "strwidth",
      "strcharpart", "strcharlen", "reverse",
      "repeat", "tolower", "toupper", "tr",
      "escape", "shellescape", "nr2char", "char2nr",
      "printf", "getline", "append", "delete",
      "setline", "getbufline", "setbufline",
      "bufloaded", "bufexists", "buflisted",
      "winnr", "bufwinnr", "tabpagenr", "winlayout",
      "getwininfo", "getbufinfo", "complete",
      "complete_add", "complete_check",
    ],
    commentSingle: '"',
    commentMulti: ["", ""],
    stringChars: ["'", '"'],
  },
};

/**
 * Retrieve a language definition by its lowercase name.
 * Supports aliases: "js" → "javascript", "ts" → "typescript", "py" → "python", etc.
 */
export function getLanguageDefinition(lang: string): LanguageDefinition | undefined {
  if (!lang) return undefined;

  const normalized = lang.toLowerCase().trim();

  // Direct lookup
  if (EXTENDED_LANGUAGES[normalized]) {
    return EXTENDED_LANGUAGES[normalized];
  }

  // Alias mapping
  const aliases: Record<string, string> = {
    js: "javascript",
    mjs: "javascript",
    cjs: "javascript",
    jsx: "jsx",
    ts: "typescript",
    tsx: "tsx",
    py: "python",
    py3: "python",
    rb: "ruby",
    rs: "rust",
    go: "go",
    golang: "go",
    sh: "bash",
    shell: "bash",
    zsh: "bash",
    fish: "bash",
    ps1: "powershell",
    psm1: "powershell",
    pssc: "powershell",
    h: "c",
    hpp: "cpp",
    cc: "cpp",
    cxx: "cpp",
    cs: "csharp",
    vb: "csharp",
    ex: "elixir",
    exs: "elixir",
    erl: "erlang",
    hrl: "erlang",
    clj: "clojure",
    cljs: "clojure",
    cljc: "clojure",
    hs: "haskell",
    lhs: "haskell",
    r: "r",
    R: "r",
    m: "matlab",
    jl: "julia",
    f: "fortran",
    f90: "fortran",
    f95: "fortran",
    f03: "fortran",
    pl: "perl",
    pm: "perl",
    php: "php",
    lua: "lua",
    vue: "vue",
    svelte: "svelte",
    vim: "vimscript",
    zig: "zig",
    nim: "nim",
    sol: "solidity",
    asm: "assembly",
    s: "assembly",
    yml: "yaml",
    toml: "toml",
    gql: "graphql",
    graphqls: "graphql",
    dockerfile: "dockerfile",
    make: "makefile",
    mk: "makefile",
    md: "markdown",
    mdx: "markdown",
    tex: "latex",
    cfg: "ini",
    conf: "ini",
    scss: "scss",
    sass: "sass",
    less: "less",
    coffee: "coffeescript",
    kt: "kotlin",
    kts: "kotlin",
    scala: "scala",
    sc: "scala",
    groovy: "groovy",
    gradle: "groovy",
    gvy: "groovy",
    swift: "swift",
    dart: "dart",
    obj: "csharp",
    mm: "objective-c",
    vi: "vimscript",
  };

  const aliased = aliases[normalized];
  if (aliased && EXTENDED_LANGUAGES[aliased]) {
    return EXTENDED_LANGUAGES[aliased];
  }

  return undefined;
}

/**
 * Returns a mapping from file extension (without dot) to language name.
 * Covers 100+ common file extensions.
 */
export function getLanguageExtensions(): Record<string, string> {
  return {
    // Web
    ".html": "html",
    ".htm": "html",
    ".xhtml": "html",
    ".shtml": "html",
    ".css": "css",
    ".js": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".jsx": "jsx",
    ".ts": "typescript",
    ".tsx": "tsx",
    ".json": "json",
    ".jsonc": "json",
    ".json5": "json",
    ".xml": "xml",
    ".xsl": "xml",
    ".xslt": "xml",
    ".xsd": "xml",
    ".svg": "xml",
    ".xaml": "xml",
    ".rss": "xml",
    ".atom": "xml",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "toml",
    ".graphql": "graphql",
    ".gql": "graphql",
    ".graphqls": "graphql",
    ".sql": "sql",
    ".mysql": "sql",
    ".psql": "sql",
    ".sqlite": "sql",
    ".sh": "bash",
    ".bash": "bash",
    ".zsh": "bash",
    ".fish": "bash",
    ".ps1": "powershell",
    ".psm1": "powershell",
    ".psd1": "powershell",
    ".bat": "powershell",
    ".cmd": "powershell",

    // Systems
    ".c": "c",
    ".h": "c",
    ".cpp": "cpp",
    ".cc": "cpp",
    ".cxx": "cpp",
    ".hpp": "cpp",
    ".hxx": "cpp",
    ".h++": "cpp",
    ".c++": "cpp",
    ".cs": "csharp",
    ".csx": "csharp",
    ".go": "go",
    ".rs": "rust",
    ".swift": "swift",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".java": "java",
    ".jar": "java",
    ".scala": "scala",
    ".sc": "scala",
    ".rb": "ruby",
    ".rbw": "ruby",
    ".gemspec": "ruby",
    ".rake": "ruby",
    ".py": "python",
    ".pyw": "python",
    ".pyi": "python",
    ".pyx": "python",

    // Functional
    ".hs": "haskell",
    ".lhs": "haskell",
    ".ex": "elixir",
    ".exs": "elixir",
    ".erl": "erlang",
    ".hrl": "erlang",
    ".clj": "clojure",
    ".cljs": "clojure",
    ".cljc": "clojure",

    // Data
    ".r": "r",
    ".R": "r",
    ".Rmd": "r",
    ".Rnw": "r",
    ".mat": "matlab",
    ".jl": "julia",
    ".f": "fortran",
    ".f90": "fortran",
    ".f95": "fortran",
    ".f03": "fortran",
    ".f08": "fortran",

    // Scripting
    ".pl": "perl",
    ".pm": "perl",
    ".t": "perl",
    ".php": "php",
    ".phtml": "php",
    ".php3": "php",
    ".php4": "php",
    ".php5": "php",
    ".php7": "php",
    ".phps": "php",
    ".lua": "lua",
    ".dart": "dart",
    ".groovy": "groovy",
    ".gradle": "groovy",
    ".gvy": "groovy",

    // Markup
    ".tex": "latex",
    ".ltx": "latex",
    ".sty": "latex",
    ".cls": "latex",
    ".bib": "latex",
    ".md": "markdown",
    ".markdown": "markdown",
    ".mdx": "markdown",
    ".mkd": "markdown",
    ".mkdn": "markdown",
    ".Dockerfile": "dockerfile",
    ".dockerignore": "dockerfile",
    ".Makefile": "makefile",
    ".mk": "makefile",
    ".mak": "makefile",
    ".ini": "ini",
    ".cfg": "ini",
    ".conf": "ini",
    ".properties": "ini",

    // Other
    ".asm": "assembly",
    ".s": "assembly",
    ".sol": "solidity",
    ".coffee": "coffeescript",
    ".litcoffee": "coffeescript",
    ".scss": "scss",
    ".sass": "sass",
    ".less": "less",

    // Additional
    ".m": "objective-c",
    ".mm": "objective-c",
    ".vue": "vue",
    ".svelte": "svelte",
    ".zig": "zig",
    ".nim": "nim",
    ".vim": "vimscript",
  };
}

/**
 * Returns a sorted array of all supported language names.
 */
export function getAllLanguageNames(): string[] {
  return Object.keys(EXTENDED_LANGUAGES)
    .map((key) => EXTENDED_LANGUAGES[key].name)
    .sort((a, b) => a.localeCompare(b));
}
